import Link from 'next/link'
import { notFound } from 'next/navigation'
import { getAdminBipById, getNextPendingBip } from '@/lib/queries/adminBips'
import { createClient } from '@/lib/supabase/server'
import { BipHeader } from '@/components/bip/BipHeader'
import { BipBody } from '@/components/bip/BipBody'
import { BipSidebar } from '@/components/bip/BipSidebar'
import { AdminActionsPanel } from '@/components/admin/AdminActionsPanel'
import type { BipStatus } from '@/lib/utils/status'

/**
 * Admin BIP review page (Plan 03-03 / ADMN-03).
 *
 * Two-column layout (mirrors public /bip/[slug]):
 *   - Main column: BipHeader + BipBody
 *   - Right column: BipSidebar mode="admin-review" (suppresses Apply CTA +
 *     Share/Bookmark) + AdminActionsPanel
 *
 * Auth is layered:
 *   - middleware.ts (Plan 03-02) blocks unauthenticated /admin/** access
 *   - app/(admin)/layout.tsx re-checks app_metadata.role === 'admin'
 *   - getAdminBipById() re-checks the role server-side (defense in depth)
 *
 * Cache: `dynamic = 'force-dynamic'` — the layout already marks the
 * segment dynamic via getClaims(), but be explicit so this page never
 * gets statically generated by mistake.
 */
export const dynamic = 'force-dynamic'

type CoordinatorRow = { full_name: string | null; contact_email: string | null }

async function getCoordinatorForBip(bipId: string): Promise<CoordinatorRow | null> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from('bips')
    .select('profiles:created_by ( full_name, contact_email )')
    .eq('id', bipId)
    .maybeSingle()
  if (error || !data) return null
  const profilesRaw = (data as { profiles?: unknown }).profiles
  const profiles = Array.isArray(profilesRaw)
    ? (profilesRaw[0] as CoordinatorRow | undefined)
    : (profilesRaw as CoordinatorRow | undefined)
  return profiles ?? null
}

export default async function ReviewBipPage(props: {
  params: Promise<{ id: string }>
}) {
  const { id } = await props.params
  const [bip, next, coordinator] = await Promise.all([
    getAdminBipById(id),
    getNextPendingBip(id),
    getCoordinatorForBip(id),
  ])
  if (!bip) notFound()

  const coordinatorName = coordinator?.full_name ?? ''

  return (
    <div className="max-w-[1200px] mx-auto px-6 py-6">
      {/* Breadcrumb row */}
      <div className="bg-white border border-border rounded-md px-4 py-3 mb-4 flex items-center justify-between">
        <Link href="/admin" className="text-sm text-eu-blue hover:underline">
          ← Back to queue
        </Link>
        <span className="text-sm text-muted">
          {next ? `Next pending: ${next.title}` : 'No more pending after this one'}
        </span>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_340px] gap-x-8">
        <div>
          <BipHeader bip={bip} />
          <BipBody bip={bip} />
        </div>
        <div className="flex flex-col gap-4">
          <BipSidebar bip={bip} mode="admin-review" />
          <AdminActionsPanel
            bipId={bip.id}
            bipTitle={bip.title}
            coordinatorName={coordinatorName}
            currentStatus={bip.status as BipStatus}
            nextPendingId={next?.id ?? null}
          />
        </div>
      </div>
    </div>
  )
}
