/**
 * Detailed ISCED-F 2013 codes used in the BIP builder (Step 1).
 *
 * 174 entries: 4-digit code + official label. Sourced from the
 * product-provided list (see task prompt). Stored as `{ code, label }`
 * so the builder can search by either and render `code — label`.
 *
 * This is separate from the 12 broad `ISCED_FIELDS` in `lib/isced.ts`
 * (homepage categories / `bips.subject_areas`). Both taxonomies coexist:
 * `subject_areas` = BipHub's 12 categories, `isced_codes` = detailed
 * ISCED-F codes for Erasmus+ reporting.
 */
export const ISCED_CODES = [
  { code: '0011', label: 'Basic programmes and qualifications' },
  { code: '0021', label: 'Literacy and numeracy' },
  { code: '0031', label: 'Personal skills and development' },
  { code: '0100', label: 'Education, not further defined' },
  { code: '0110', label: 'Education, not further defined' },
  { code: '0111', label: 'Education science' },
  { code: '0112', label: 'Training for pre-school teachers' },
  { code: '0113', label: 'Teacher training without subject specialisation' },
  { code: '0114', label: 'Teacher training with subject specialisation' },
  { code: '0118', label: 'Education, inter-disciplinary programmes' },
  { code: '0119', label: 'Education, not elsewhere classified' },
  { code: '0188', label: 'Education, inter-disciplinary programmes' },
  { code: '0200', label: 'Arts and humanities, not further defined' },
  { code: '0210', label: 'Arts, not further defined' },
  { code: '0211', label: 'Audio-visual techniques and media production' },
  { code: '0212', label: 'Fashion, interior and industrial design' },
  { code: '0213', label: 'Fine arts' },
  { code: '0214', label: 'Handicrafts' },
  { code: '0215', label: 'Music and performing arts' },
  { code: '0218', label: 'Arts, inter-disciplinary programmes' },
  { code: '0219', label: 'Arts, not elsewhere classified' },
  { code: '0220', label: 'Humanities (except languages), not further defined' },
  { code: '0221', label: 'Religion and theology' },
  { code: '0222', label: 'History and archaeology' },
  { code: '0223', label: 'Philosophy and ethics' },
  { code: '0228', label: 'Humanities (except languages), inter-disciplinary programmes' },
  { code: '0229', label: 'Humanities (except languages), not elsewhere classified' },
  { code: '0230', label: 'Languages, not further defined' },
  { code: '0231', label: 'Language acquisition' },
  { code: '0232', label: 'Literature and linguistics' },
  { code: '0238', label: 'Languages, inter-disciplinary programmes' },
  { code: '0239', label: 'Languages, not elsewhere classified' },
  { code: '0288', label: 'Arts and humanities, inter-disciplinary programmes' },
  { code: '0300', label: 'Social sciences, journalism and information, not further defined' },
  { code: '0310', label: 'Social and behavioural sciences, not further defined' },
  { code: '0311', label: 'Economics' },
  { code: '0312', label: 'Political sciences and civics' },
  { code: '0313', label: 'Psychology' },
  { code: '0314', label: 'Sociology and cultural studies' },
  { code: '0318', label: 'Social and behavioural sciences, inter-disciplinary programmes' },
  { code: '0319', label: 'Social and behavioural sciences, not elsewhere classified' },
  { code: '0320', label: 'Journalism and information, not further defined' },
  { code: '0321', label: 'Journalism and reporting' },
  { code: '0322', label: 'Library, information and archival studies' },
  { code: '0328', label: 'Journalism and information, inter-disciplinary programmes' },
  { code: '0329', label: 'Journalism and information, not elsewhere classified' },
  { code: '0388', label: 'Social sciences, journalism and information, inter-disciplinary programmes' },
  { code: '0400', label: 'Business, administration and law, not further defined' },
  { code: '0410', label: 'Business and administration, not further defined' },
  { code: '0411', label: 'Accounting and taxation' },
  { code: '0412', label: 'Finance, banking and insurance' },
  { code: '0413', label: 'Management and administration' },
  { code: '0414', label: 'Marketing and advertising' },
  { code: '0415', label: 'Secretarial and office work' },
  { code: '0416', label: 'Wholesale and retail sales' },
  { code: '0417', label: 'Work skills' },
  { code: '0418', label: 'Business and administration, inter-disciplinary programmes' },
  { code: '0419', label: 'Business and administration, not elsewhere classified' },
  { code: '0420', label: 'Law, not further defined' },
  { code: '0421', label: 'Law' },
  { code: '0428', label: 'Law, inter-disciplinary programmes' },
  { code: '0429', label: 'Law, not elsewhere classified' },
  { code: '0488', label: 'Business, administration and law, inter-disciplinary programmes' },
  { code: '0500', label: 'Natural sciences, mathematics and statistics, not further defined' },
  { code: '0510', label: 'Biological and related sciences, not further defined' },
  { code: '0511', label: 'Biology' },
  { code: '0512', label: 'Biochemistry' },
  { code: '0518', label: 'Biological and related sciences, inter-disciplinary programmes' },
  { code: '0519', label: 'Biological and related sciences, not elsewhere classified' },
  { code: '0520', label: 'Environment, not further defined' },
  { code: '0521', label: 'Environmental sciences' },
  { code: '0522', label: 'Natural environments and wildlife' },
  { code: '0528', label: 'Environment, inter-disciplinary programmes' },
  { code: '0529', label: 'Environment, not elsewhere classified' },
  { code: '0530', label: 'Physical sciences, not further defined' },
  { code: '0531', label: 'Chemistry' },
  { code: '0532', label: 'Earth sciences' },
  { code: '0533', label: 'Physics' },
  { code: '0538', label: 'Physical sciences, inter-disciplinary programmes' },
  { code: '0539', label: 'Physical sciences, not elsewhere classified' },
  { code: '0540', label: 'Mathematics and statistics, not further defined' },
  { code: '0541', label: 'Mathematics' },
  { code: '0542', label: 'Statistics' },
  { code: '0548', label: 'Mathematics and statistics, inter-disciplinary programmes' },
  { code: '0549', label: 'Mathematics and statistics, not elsewhere classified' },
  { code: '0588', label: 'Natural sciences, mathematics and statistics, inter-disciplinary programmes' },
  { code: '0600', label: 'Information and Communication Technologies (ICTs), not further defined' },
  { code: '0610', label: 'Information and Communication Technologies (ICTs), not further defined' },
  { code: '0611', label: 'Computer use' },
  { code: '0612', label: 'Database and network design and administration' },
  { code: '0613', label: 'Software and applications development and analysis' },
  { code: '0618', label: 'Information and Communication Technologies (ICTs), inter-disciplinary programmes' },
  { code: '0619', label: 'Information and Communication Technologies (ICTs), not elsewhere classified' },
  { code: '0688', label: 'Information and Communication Technologies (ICTs), inter-disciplinary programmes' },
  { code: '0700', label: 'Engineering, manufacturing and construction, not further defined' },
  { code: '0710', label: 'Engineering and engineering trades, not further defined' },
  { code: '0711', label: 'Chemical engineering and processes' },
  { code: '0712', label: 'Environmental protection technology' },
  { code: '0713', label: 'Electricity and energy' },
  { code: '0714', label: 'Electronics and automation' },
  { code: '0715', label: 'Mechanics and metal trades' },
  { code: '0716', label: 'Motor vehicles, ships and aircraft' },
  { code: '0718', label: 'Engineering and engineering trades, inter-disciplinary programmes' },
  { code: '0719', label: 'Engineering and engineering trades, not elsewhere classified' },
  { code: '0720', label: 'Manufacturing and processing, not further defined' },
  { code: '0721', label: 'Food processing' },
  { code: '0722', label: 'Materials (glass, paper, plastic and wood)' },
  { code: '0723', label: 'Textiles (clothes, footwear and leather)' },
  { code: '0724', label: 'Mining and extraction' },
  { code: '0728', label: 'Manufacturing and processing, inter-disciplinary programmes' },
  { code: '0729', label: 'Manufacturing and processing, not elsewhere classified' },
  { code: '0730', label: 'Architecture and construction, not further defined' },
  { code: '0731', label: 'Architecture and town planning' },
  { code: '0732', label: 'Building and civil engineering' },
  { code: '0738', label: 'Architecture and construction, inter-disciplinary programmes' },
  { code: '0739', label: 'Architecture and construction, not elsewhere classified' },
  { code: '0788', label: 'Engineering, manufacturing and construction, inter-disciplinary programmes' },
  { code: '0800', label: 'Agriculture, forestry, fisheries and veterinary, not further defined' },
  { code: '0810', label: 'Agriculture, not further defined' },
  { code: '0811', label: 'Crop and livestock production' },
  { code: '0812', label: 'Horticulture' },
  { code: '0818', label: 'Agriculture, inter-disciplinary programmes' },
  { code: '0819', label: 'Agriculture, not elsewhere classified' },
  { code: '0820', label: 'Forestry, not further defined' },
  { code: '0821', label: 'Forestry' },
  { code: '0828', label: 'Forestry, inter-disciplinary programmes' },
  { code: '0829', label: 'Forestry, not elsewhere classified' },
  { code: '0830', label: 'Fisheries, not further defined' },
  { code: '0831', label: 'Fisheries' },
  { code: '0838', label: 'Fisheries, inter-disciplinary programmes' },
  { code: '0839', label: 'Fisheries, not elsewhere classified' },
  { code: '0840', label: 'Veterinary, not further defined' },
  { code: '0841', label: 'Veterinary' },
  { code: '0848', label: 'Veterinary, inter-disciplinary programmes' },
  { code: '0849', label: 'Veterinary, not elsewhere classified' },
  { code: '0888', label: 'Agriculture, forestry, fisheries and veterinary, inter-disciplinary programmes' },
  { code: '0900', label: 'Health and welfare, not further defined' },
  { code: '0910', label: 'Health, not further defined' },
  { code: '0911', label: 'Dental studies' },
  { code: '0912', label: 'Medicine' },
  { code: '0913', label: 'Nursing and midwifery' },
  { code: '0914', label: 'Medical diagnostic and treatment technology' },
  { code: '0915', label: 'Therapy and rehabilitation' },
  { code: '0916', label: 'Pharmacy' },
  { code: '0917', label: 'Traditional and complementary medicine and therapy' },
  { code: '0918', label: 'Health, inter-disciplinary programmes' },
  { code: '0919', label: 'Health, not elsewhere classified' },
  { code: '0920', label: 'Welfare, not further defined' },
  { code: '0921', label: 'Care of the elderly and of disabled adults' },
  { code: '0922', label: 'Child care and youth services' },
  { code: '0923', label: 'Social work and counselling' },
  { code: '0928', label: 'Welfare, inter-disciplinary programmes' },
  { code: '0929', label: 'Welfare, not elsewhere classified' },
  { code: '0988', label: 'Health and welfare, inter-disciplinary programmes' },
  { code: '1000', label: 'Services, not further defined' },
  { code: '1010', label: 'Personal services, not further defined' },
  { code: '1011', label: 'Domestic services' },
  { code: '1012', label: 'Hair and beauty services' },
  { code: '1013', label: 'Hotel, restaurants and catering' },
  { code: '1014', label: 'Sports' },
  { code: '1015', label: 'Travel, tourism and leisure' },
  { code: '1018', label: 'Personal services, inter-disciplinary programmes' },
  { code: '1019', label: 'Personal services, not elsewhere classified' },
  { code: '1020', label: 'Hygiene and occupational health services, not further defined' },
  { code: '1021', label: 'Community sanitation' },
  { code: '1022', label: 'Occupational health and safety' },
  { code: '1028', label: 'Hygiene and occupational health services, inter-disciplinary programmes' },
  { code: '1029', label: 'Hygiene and occupational health services, not elsewhere classified' },
  { code: '1030', label: 'Security services, not further defined' },
  { code: '1031', label: 'Military and defence' },
  { code: '1032', label: 'Protection of persons and property' },
  { code: '1038', label: 'Security services, inter-disciplinary programmes' },
  { code: '1039', label: 'Security services, not elsewhere classified' },
  { code: '1040', label: 'Transport services, not further defined' },
  { code: '1041', label: 'Transport services' },
  { code: '1048', label: 'Transport services, inter-disciplinary programmes' },
  { code: '1049', label: 'Transport services, not elsewhere classified' },
  { code: '1088', label: 'Services, inter-disciplinary programmes' },
  { code: '9999', label: 'Field of Study unknown - Not elsewhere Classified (Used to group a large number of degrees that you do not want to specify further in terms of field of study)' },
] as const

export type IscedCode = (typeof ISCED_CODES)[number]['code']

export const ISCED_CODE_SET: ReadonlySet<string> = new Set(
  ISCED_CODES.map((c) => c.code),
)

export const ISCED_CODE_BY_ID: Readonly<Record<string, string>> =
  Object.fromEntries(ISCED_CODES.map((c) => [c.code, c.label])) as Record<string, string>
