-- 00036_universities_name_cleanup.sql
-- Tidies display names imported by 00035 that carried the institution's full,
-- quote-laden legal name (e.g. D MUNCHEN07). Two transforms:
--   1. a name that LEADS with a quoted trading name AND is long -> the trade name
--   2. otherwise, embedded quote characters -> spaces.
-- legal_name is untouched (kept for search). Idempotent: each UPDATE no-ops if
-- the name is already clean. 185 rows affected.

update public.universities set name = 'Universiteti Eqrem Çabej i Gjirokastrës'
 where erasmus_code = 'AL GIJROKA01' and name <> 'Universiteti Eqrem Çabej i Gjirokastrës';
update public.universities set name = 'Artesis Plantijn Hogeschool Antwerpen'
 where erasmus_code = 'B ANTWERP62' and name <> 'Artesis Plantijn Hogeschool Antwerpen';
update public.universities set name = 'Visoka skola Logos centar u Mostaru'
 where erasmus_code = 'BA MOSTAR03' and name <> 'Visoka skola Logos centar u Mostaru';
update public.universities set name = 'Vishe Voennovazdushno uchilishte Georgi Benkovski'
 where erasmus_code = 'BG PLEVEN02' and name <> 'Vishe Voennovazdushno uchilishte Georgi Benkovski';
update public.universities set name = 'National Academy of Music Prof.pancho Vladigerov'
 where erasmus_code = 'BG SOFIA13' and name <> 'National Academy of Music Prof.pancho Vladigerov';
update public.universities set name = 'Higher School of Transport Todor Kableshkov -Sofia'
 where erasmus_code = 'BG SOFIA22' and name <> 'Higher School of Transport Todor Kableshkov -Sofia';
update public.universities set name = 'Vishe Uchilishte Po Telekomunikatsi i Poshti'
 where erasmus_code = 'BG SOFIA28' and name <> 'Vishe Uchilishte Po Telekomunikatsi i Poshti';
update public.universities set name = 'National Defence College G. S. Rakovski'
 where erasmus_code = 'BG SOFIA34' and name <> 'National Defence College G. S. Rakovski';
update public.universities set name = 'Teatralen kolej Lyuben Grois'
 where erasmus_code = 'BG SOFIA35' and name <> 'Teatralen kolej Lyuben Grois';
update public.universities set name = 'Hochschule für Musik Hanns Eisler Berlin'
 where erasmus_code = 'D BERLIN16' and name <> 'Hochschule für Musik Hanns Eisler Berlin';
update public.universities set name = 'FOM Hochschule für Oekonomie & Management gemeinnützige GmbH'
 where erasmus_code = 'D ESSEN03' and name <> 'FOM Hochschule für Oekonomie & Management gemeinnützige GmbH';
update public.universities set name = 'Christian-albrechts-universitaet Zu Kiel'
 where erasmus_code = 'D KIEL01' and name <> 'Christian-albrechts-universitaet Zu Kiel';
update public.universities set name = 'Katholische Stiftungshochschule München'
 where erasmus_code = 'D MUNCHEN07' and name <> 'Katholische Stiftungshochschule München';
update public.universities set name = 'Bergische Universitaet Wuppertal'
 where erasmus_code = 'D WUPPERT01' and name <> 'Bergische Universitaet Wuppertal';
update public.universities set name = 'Instituto de Educación Secundaria Cotes Baixes'
 where erasmus_code = 'E ALICANT21' and name <> 'Instituto de Educación Secundaria Cotes Baixes';
update public.universities set name = 'Instituto de Educación Secundaria Sol de Portocarrero'
 where erasmus_code = 'E ALMERIA18' and name <> 'Instituto de Educación Secundaria Sol de Portocarrero';
update public.universities set name = 'Centro Integrado de Formación Profesional de Ávila - Vocational Training Integrated Centre of Ávila'
 where erasmus_code = 'E AVILA06' and name <> 'Centro Integrado de Formación Profesional de Ávila - Vocational Training Integrated Centre of Ávila';
update public.universities set name = 'Instituto de Enseñanza Secundaria Isabel de Castilla'
 where erasmus_code = 'E AVILA12' and name <> 'Instituto de Enseñanza Secundaria Isabel de Castilla';
update public.universities set name = 'Conservatorio Superior de Música Bonifacio Gil'
 where erasmus_code = 'E BADAJOZ39' and name <> 'Conservatorio Superior de Música Bonifacio Gil';
update public.universities set name = 'Fundación Dolores Sopeña Badajoz'
 where erasmus_code = 'E BADAJOZ40' and name <> 'Fundación Dolores Sopeña Badajoz';
update public.universities set name = 'Institut Baix Montseny'
 where erasmus_code = 'E BARCELO244' and name <> 'Institut Baix Montseny';
update public.universities set name = 'Centre Català Comercial'
 where erasmus_code = 'E BARCELO294' and name <> 'Centre Català Comercial';
update public.universities set name = 'Ins Anna Gironella de Mundet'
 where erasmus_code = 'E BARCELO62' and name <> 'Ins Anna Gironella de Mundet';
update public.universities set name = 'Escuela Superior de Arte Dramático y Danza de Euskadi Dantzerti'
 where erasmus_code = 'E BILBAO73' and name <> 'Escuela Superior de Arte Dramático y Danza de Euskadi Dantzerti';
update public.universities set name = 'Instituto de Educación Secundaria Ágora'
 where erasmus_code = 'E CACERES02' and name <> 'Instituto de Educación Secundaria Ágora';
update public.universities set name = 'Instituto de Educacion Secundaria Albalat'
 where erasmus_code = 'E CACERES08' and name <> 'Instituto de Educacion Secundaria Albalat';
update public.universities set name = 'Instituto de Educación Secundaria José Luis Tejada Peluffo'
 where erasmus_code = 'E CADIZ56' and name <> 'Instituto de Educación Secundaria José Luis Tejada Peluffo';
update public.universities set name = 'Conservatorio Superior de Música Salvador Seguí de Castellón'
 where erasmus_code = 'E CASTELL13' and name <> 'Conservatorio Superior de Música Salvador Seguí de Castellón';
update public.universities set name = 'Instituto de Enseñanza Secundaria ANTONIO CALVIN'
 where erasmus_code = 'E CIUDA R09' and name <> 'Instituto de Enseñanza Secundaria ANTONIO CALVIN';
update public.universities set name = 'Colegio Salesianos San Juan Bosco'
 where erasmus_code = 'E CIUDA R16' and name <> 'Colegio Salesianos San Juan Bosco';
update public.universities set name = 'Conservatorio Superior de musica Rafael Orozco Cordoba'
 where erasmus_code = 'E CORDOBA04' and name <> 'Conservatorio Superior de musica Rafael Orozco Cordoba';
update public.universities set name = 'Escuela Superior de Arte Dramático Miguel Salcedo Hierro de Córdoba'
 where erasmus_code = 'E CORDOBA05' and name <> 'Escuela Superior de Arte Dramático Miguel Salcedo Hierro de Córdoba';
update public.universities set name = 'Ies el Tablero'
 where erasmus_code = 'E CORDOBA51' and name <> 'Ies el Tablero';
update public.universities set name = 'Ies Diego Torrente Pérez'
 where erasmus_code = 'E CUENCA17' and name <> 'Ies Diego Torrente Pérez';
update public.universities set name = 'Real Conservatorio Superior de Música Victoria Eugenia'
 where erasmus_code = 'E GRANADA04' and name <> 'Real Conservatorio Superior de Música Victoria Eugenia';
update public.universities set name = 'Fundación Educativa José Gras. Colegio Cristo Rey Granada'
 where erasmus_code = 'E GRANADA55' and name <> 'Fundación Educativa José Gras. Colegio Cristo Rey Granada';
update public.universities set name = 'C.I.F.P. Profesor José Luis Graíño'
 where erasmus_code = 'E HUELVA26' and name <> 'C.I.F.P. Profesor José Luis Graíño';
update public.universities set name = 'Instituto de Educación Secundaria La Palma'
 where erasmus_code = 'E HUELVA28' and name <> 'Instituto de Educación Secundaria La Palma';
update public.universities set name = 'Instituto de Educación Secundaria Hnos. Argensola'
 where erasmus_code = 'E HUESCA14' and name <> 'Instituto de Educación Secundaria Hnos. Argensola';
update public.universities set name = 'Escuela de Arte José Nogué'
 where erasmus_code = 'E JAEN15' and name <> 'Escuela de Arte José Nogué';
update public.universities set name = 'Escuela de Arte Casa de las Torres'
 where erasmus_code = 'E JAEN18' and name <> 'Escuela de Arte Casa de las Torres';
update public.universities set name = 'Centro Privado Plurilingüe Liceo La Paz'
 where erasmus_code = 'E LA CORU37' and name <> 'Centro Privado Plurilingüe Liceo La Paz';
update public.universities set name = 'Centro de Formación Profesional Maria Auxiliadora'
 where erasmus_code = 'E LEON05' and name <> 'Centro de Formación Profesional Maria Auxiliadora';
update public.universities set name = 'Escola Agrària Alfarràs'
 where erasmus_code = 'E LLEIDA18' and name <> 'Escola Agrària Alfarràs';
update public.universities set name = 'Col·Legi Episcopal Mare de Déu de L''acadèmia'
 where erasmus_code = 'E LLEIDA23' and name <> 'Col·Legi Episcopal Mare de Déu de L''acadèmia';
update public.universities set name = 'Instituto de Educación Secundaria Manuel Bartolomé Cossío'
 where erasmus_code = 'E LOGRONO20' and name <> 'Instituto de Educación Secundaria Manuel Bartolomé Cossío';
update public.universities set name = 'Instituto de Educación Secundaria Gregorio Fernández'
 where erasmus_code = 'E LUGO14' and name <> 'Instituto de Educación Secundaria Gregorio Fernández';
update public.universities set name = 'Ies da Terra Chá José Trapero Pardo'
 where erasmus_code = 'E LUGO22' and name <> 'Ies da Terra Chá José Trapero Pardo';
update public.universities set name = 'Instituto de Educacion Secundaria Santa Engracia'
 where erasmus_code = 'E MADRID135' and name <> 'Instituto de Educacion Secundaria Santa Engracia';
update public.universities set name = 'Instituto de Educación Secundaria Palomeras-vallecas'
 where erasmus_code = 'E MADRID63' and name <> 'Instituto de Educación Secundaria Palomeras-vallecas';
update public.universities set name = 'Ies Francisco Tomas y Valiente'
 where erasmus_code = 'E MADRID73' and name <> 'Ies Francisco Tomas y Valiente';
update public.universities set name = 'Conservatorio Superior de Música Manuel Massotti Littel'
 where erasmus_code = 'E MURCIA02' and name <> 'Conservatorio Superior de Música Manuel Massotti Littel';
update public.universities set name = 'Instituto de Educación Secundaria José Planes'
 where erasmus_code = 'E MURCIA19' and name <> 'Instituto de Educación Secundaria José Planes';
update public.universities set name = 'Instituto de Educación Secundaria Villa de Abarán'
 where erasmus_code = 'E MURCIA22' and name <> 'Instituto de Educación Secundaria Villa de Abarán';
update public.universities set name = 'Instituto de Educacion Secundaria El Bohio'
 where erasmus_code = 'E MURCIA35' and name <> 'Instituto de Educacion Secundaria El Bohio';
update public.universities set name = 'Instituto de Educación Secundaria Sanje'
 where erasmus_code = 'E MURCIA69' and name <> 'Instituto de Educación Secundaria Sanje';
update public.universities set name = 'Instituto de Educación Secundaria Gil de Junterón'
 where erasmus_code = 'E MURCIA76' and name <> 'Instituto de Educación Secundaria Gil de Junterón';
update public.universities set name = 'Conservatorio Superior de Música Eduardo Martínez Torner del Principado de Asturias'
 where erasmus_code = 'E OVIEDO03' and name <> 'Conservatorio Superior de Música Eduardo Martínez Torner del Principado de Asturias';
update public.universities set name = 'Escuela de Arte y Superior de Conservación y Restauración de Bienes Culturales Mariano Timón de Palencia'
 where erasmus_code = 'E PALENCI09' and name <> 'Escuela de Arte y Superior de Conservación y Restauración de Bienes Culturales Mariano Timón de Palencia';
update public.universities set name = 'Fundació Per Als Estudis de Música i Arts Escèniques de les Illes Balears - Escola Superior D''art Dramàtic de les Illes Balears'
 where erasmus_code = 'E PALMA25' and name <> 'Fundació Per Als Estudis de Música i Arts Escèniques de les Illes Balears - Escola Superior D''art Dramàtic de les Illes Balears';
update public.universities set name = 'Instituto de Educacion Secundaria Toki Ona'
 where erasmus_code = 'E PAMPLON04' and name <> 'Instituto de Educacion Secundaria Toki Ona';
update public.universities set name = 'Centro Integrado Escuela Sanitaria Técnico Profesional de Navarra - ESTNA'
 where erasmus_code = 'E PAMPLON10' and name <> 'Centro Integrado Escuela Sanitaria Técnico Profesional de Navarra - ESTNA';
update public.universities set name = 'Centro Integrado de Administración, Comercio e Informática María Ana Sanz'
 where erasmus_code = 'E PAMPLON12' and name <> 'Centro Integrado de Administración, Comercio e Informática María Ana Sanz';
update public.universities set name = 'Centro Integrado Escuela de Educadoras y Educadores - Hezitzaile Eskola'
 where erasmus_code = 'E PAMPLON22' and name <> 'Centro Integrado Escuela de Educadoras y Educadores - Hezitzaile Eskola';
update public.universities set name = 'Instituto de Educacion Secundaria Cantabria'
 where erasmus_code = 'E SANTAND05' and name <> 'Instituto de Educacion Secundaria Cantabria';
update public.universities set name = 'Instituto de Educación Secundaria María Moliner'
 where erasmus_code = 'E SEGOVIA04' and name <> 'Instituto de Educación Secundaria María Moliner';
update public.universities set name = 'Escuela de Arte y Superior de Diseño Casa de Los Picos de Segovia'
 where erasmus_code = 'E SEGOVIA06' and name <> 'Escuela de Arte y Superior de Diseño Casa de Los Picos de Segovia';
update public.universities set name = 'Conservatorio Superior de Música Manuel Castillo de Sevilla'
 where erasmus_code = 'E SEVILLA04' and name <> 'Conservatorio Superior de Música Manuel Castillo de Sevilla';
update public.universities set name = 'Ies Vega del Turia'
 where erasmus_code = 'E TERUEL03' and name <> 'Ies Vega del Turia';
update public.universities set name = 'Escuela de Arte Toledo'
 where erasmus_code = 'E TOLEDO12' and name <> 'Escuela de Arte Toledo';
update public.universities set name = 'Instituto de Enseñanza Secundaria MIGUEL HERRERO PEREDA'
 where erasmus_code = 'E TORRELA01' and name <> 'Instituto de Enseñanza Secundaria MIGUEL HERRERO PEREDA';
update public.universities set name = 'Centro Integrado Politécnico ETI'
 where erasmus_code = 'E TUDELA01' and name <> 'Centro Integrado Politécnico ETI';
update public.universities set name = 'Instituto Enseñanza Secundaria Pere Boïl'
 where erasmus_code = 'E VALENCI30' and name <> 'Instituto Enseñanza Secundaria Pere Boïl';
update public.universities set name = 'Conservatori Superior de Música Joaquín Rodrigo de Valencia'
 where erasmus_code = 'E VALENCI67' and name <> 'Conservatori Superior de Música Joaquín Rodrigo de Valencia';
update public.universities set name = 'C.i.f.p. Ciudad Jardin'
 where erasmus_code = 'E VITORIA07' and name <> 'C.i.f.p. Ciudad Jardin';
update public.universities set name = 'Centro Integrado de Aprendizajes Virtuales y Digitalizados/Ikaskuntza Birtual Eta Digitalizatuetarako Lanbide Heziketako Ikastetxe Bateratua'
 where erasmus_code = 'E VITORIA25' and name <> 'Centro Integrado de Aprendizajes Virtuales y Digitalizados/Ikaskuntza Birtual Eta Digitalizatuetarako Lanbide Heziketako Ikastetxe Bateratua';
update public.universities set name = 'Centro Integrado de Formación Profesional Ciudad de Zamora'
 where erasmus_code = 'E ZAMORA03' and name <> 'Centro Integrado de Formación Profesional Ciudad de Zamora';
update public.universities set name = 'Instituto de Educación Secundaria Avempace'
 where erasmus_code = 'E ZARAGOZ12' and name <> 'Instituto de Educación Secundaria Avempace';
update public.universities set name = 'Instituto Enseñanza Secundaria Ítaca'
 where erasmus_code = 'E ZARAGOZ25' and name <> 'Instituto Enseñanza Secundaria Ítaca';
update public.universities set name = 'Institut Mines Telecom, Ecole Nationale Superieure des Mines Albi Carmaux'
 where erasmus_code = 'F ALBI05' and name <> 'Institut Mines Telecom, Ecole Nationale Superieure des Mines Albi Carmaux';
update public.universities set name = 'Pôle supérieur d''enseignement artistique Aubervilliers La Courneuve Seine-Saint-Denis Ile-de-France dit Pôle Sup''93'
 where erasmus_code = 'F BOBIGNY05' and name <> 'Pôle supérieur d''enseignement artistique Aubervilliers La Courneuve Seine-Saint-Denis Ile-de-France dit Pôle Sup''93';
update public.universities set name = 'Lycee Professionnel La Providence'
 where erasmus_code = 'F CHOLET03' and name <> 'Lycee Professionnel La Providence';
update public.universities set name = 'EPLEFPA Les sillons de Haute Alsace'
 where erasmus_code = 'F COLMAR07' and name <> 'EPLEFPA Les sillons de Haute Alsace';
update public.universities set name = 'Lycee D''enseignement General Et Technologique Monchapet'
 where erasmus_code = 'F DIJON04' and name <> 'Lycee D''enseignement General Et Technologique Monchapet';
update public.universities set name = 'Lycée Professionnel Clément Ader'
 where erasmus_code = 'F EVREUX13' and name <> 'Lycée Professionnel Clément Ader';
update public.universities set name = 'Lycée polyvalent Flora Tristan'
 where erasmus_code = 'F FONTAIN02' and name <> 'Lycée polyvalent Flora Tristan';
update public.universities set name = 'Lycée Félix Le Dantec'
 where erasmus_code = 'F LANNION05' and name <> 'Lycée Félix Le Dantec';
update public.universities set name = 'Institution Notre Dame de la Providence'
 where erasmus_code = 'F LILLE113' and name <> 'Institution Notre Dame de la Providence';
update public.universities set name = 'Eplefpa Edgar Faure - Montmorot'
 where erasmus_code = 'F LONS LE07' and name <> 'Eplefpa Edgar Faure - Montmorot';
update public.universities set name = 'Groupe scolaire Saint-Louis - Notre Dame de La Paix Ogec du Levant'
 where erasmus_code = 'F LORIENT11' and name <> 'Groupe scolaire Saint-Louis - Notre Dame de La Paix Ogec du Levant';
update public.universities set name = 'Conservatoire National Superieur Demusique Et de Danse de Lyon'
 where erasmus_code = 'F LYON24' and name <> 'Conservatoire National Superieur Demusique Et de Danse de Lyon';
update public.universities set name = 'Lycee des Metiers Louise Labe'
 where erasmus_code = 'F LYON99' and name <> 'Lycee des Metiers Louise Labe';
update public.universities set name = 'Institut de Formation Chr Metz'
 where erasmus_code = 'F METZ33' and name <> 'Institut de Formation Chr Metz';
update public.universities set name = 'Institut de Formation En Soins Infirmiers du Centre Hospitalier de Montauban'
 where erasmus_code = 'F MONTAUB09' and name <> 'Institut de Formation En Soins Infirmiers du Centre Hospitalier de Montauban';
update public.universities set name = 'Lycee Enseignement Professionnel Agricole Prive'
 where erasmus_code = 'F NANTES54' and name <> 'Lycee Enseignement Professionnel Agricole Prive';
update public.universities set name = 'Etablissement Public Local d''Enseignement et de Formation Professionnelle agricole du Morvan'
 where erasmus_code = 'F NEVERS13' and name <> 'Etablissement Public Local d''Enseignement et de Formation Professionnelle agricole du Morvan';
update public.universities set name = 'Ecole Duperré Paris'
 where erasmus_code = 'F PARIS026' and name <> 'Ecole Duperré Paris';
update public.universities set name = 'Lycée polyvalent Jean Lurçat'
 where erasmus_code = 'F PERPIGN03' and name <> 'Lycée polyvalent Jean Lurçat';
update public.universities set name = 'Eplefpa Kyoto'
 where erasmus_code = 'F POITIER38' and name <> 'Eplefpa Kyoto';
update public.universities set name = 'EPLEFPA de MAMIROLLE-POLIGNY ENILEA'
 where erasmus_code = 'F POLIGNY01' and name <> 'EPLEFPA de MAMIROLLE-POLIGNY ENILEA';
update public.universities set name = 'EPLEFPA de Quimper Brehoulou'
 where erasmus_code = 'F QUIMPER14' and name <> 'EPLEFPA de Quimper Brehoulou';
update public.universities set name = 'Legt Monteil'
 where erasmus_code = 'F RODEZ01' and name <> 'Legt Monteil';
update public.universities set name = 'Association Educative La Salle St Louis Ste Barbe (de l''Ensemble Scolaire St Louis Ste Barbe)'
 where erasmus_code = 'F ST ETIE24' and name <> 'Association Educative La Salle St Louis Ste Barbe (de l''Ensemble Scolaire St Louis Ste Barbe)';
update public.universities set name = 'Lycee General Technologique Evariste de Parny'
 where erasmus_code = 'F ST PAUL06' and name <> 'Lycee General Technologique Evariste de Parny';
update public.universities set name = 'ISSEC PIGIER (ADMINISTRATION AND ACOUNTING TECHNICAL SCHOOL)Institut Spécialisé de Secrétariat et d''Etudes Comptables'
 where erasmus_code = 'F TOULOUS118' and name <> 'ISSEC PIGIER (ADMINISTRATION AND ACOUNTING TECHNICAL SCHOOL)Institut Spécialisé de Secrétariat et d''Etudes Comptables';
update public.universities set name = 'Lycée professionnel Gabriel Péri'
 where erasmus_code = 'F TOULOUS131' and name <> 'Lycée professionnel Gabriel Péri';
update public.universities set name = 'Association éducative Notre Dame Le Ménimur'
 where erasmus_code = 'F VANNES10' and name <> 'Association éducative Notre Dame Le Ménimur';
update public.universities set name = 'Conservatorio Arturo Toscanini di Ribera'
 where erasmus_code = 'I AGRIGEN02' and name <> 'Conservatorio Arturo Toscanini di Ribera';
update public.universities set name = 'Scuola Superiore per Mediatori Linguistici Agorà Mundi'
 where erasmus_code = 'I AGRIGEN03' and name <> 'Scuola Superiore per Mediatori Linguistici Agorà Mundi';
update public.universities set name = 'Conservatorio di Musica A. Vivaldi'
 where erasmus_code = 'I ALESSAN01' and name <> 'Conservatorio di Musica A. Vivaldi';
update public.universities set name = 'Conservatorio di musica Niccolò Piccinni - Bari'
 where erasmus_code = 'I BARI03' and name <> 'Conservatorio di musica Niccolò Piccinni - Bari';
update public.universities set name = 'I.t.s. Antonio Cuccovillo Sistema Meccanico-meccatronico'
 where erasmus_code = 'I BARI07' and name <> 'I.t.s. Antonio Cuccovillo Sistema Meccanico-meccatronico';
update public.universities set name = 'Conservatorio di musica Claudio Monteverdi Musik-Konservatorium Bolzano-Bozen'
 where erasmus_code = 'I BOLZANO02' and name <> 'Conservatorio di musica Claudio Monteverdi Musik-Konservatorium Bolzano-Bozen';
update public.universities set name = 'Istituto Ad Ordinamento Universitario Scuola Europea Salvo D''acquisto'
 where erasmus_code = 'I BORGOM01' and name <> 'Istituto Ad Ordinamento Universitario Scuola Europea Salvo D''acquisto';
update public.universities set name = 'Conservatorio Statale di Musica L. Perosi Campobasso'
 where erasmus_code = 'I CAMPOBA03' and name <> 'Conservatorio Statale di Musica L. Perosi Campobasso';
update public.universities set name = 'Istituto Superiore di Studi Musicali Vincenzo Bellini Catania'
 where erasmus_code = 'I CATANIA06' and name <> 'Istituto Superiore di Studi Musicali Vincenzo Bellini Catania';
update public.universities set name = 'Conservatorio di Musica Stanislao Giacomantonio'
 where erasmus_code = 'I COSENZA03' and name <> 'Conservatorio di Musica Stanislao Giacomantonio';
update public.universities set name = 'Conservatorio Statale di Musica G.b. Pergolesi - Fermo'
 where erasmus_code = 'I FERMO01' and name <> 'Conservatorio Statale di Musica G.b. Pergolesi - Fermo';
update public.universities set name = 'Conservatorio Statale di Musica G. Frescobaldi Ferrara'
 where erasmus_code = 'I FERRARA02' and name <> 'Conservatorio Statale di Musica G. Frescobaldi Ferrara';
update public.universities set name = 'Conservatorio di Musica Luigi Cherubini'
 where erasmus_code = 'I FIRENZE04' and name <> 'Conservatorio di Musica Luigi Cherubini';
update public.universities set name = 'Conservatorio Statale di Musica Umberto Giordano'
 where erasmus_code = 'I FOGGIA02' and name <> 'Conservatorio Statale di Musica Umberto Giordano';
update public.universities set name = 'Conservatorio di Musica L. Refice'
 where erasmus_code = 'I FROSINO02' and name <> 'Conservatorio di Musica L. Refice';
update public.universities set name = 'Accademia di Belle Arti Statale Ligustica'
 where erasmus_code = 'I GENOVA03' and name <> 'Accademia di Belle Arti Statale Ligustica';
update public.universities set name = 'Stituto Tecnologico Superiore e a T Eccellenza Agroalimentare Toscana Academy'
 where erasmus_code = 'I GROSSETO01' and name <> 'Stituto Tecnologico Superiore e a T Eccellenza Agroalimentare Toscana Academy';
update public.universities set name = 'Conservatorio statale Pietro Mascagni'
 where erasmus_code = 'I LIVORNO01' and name <> 'Conservatorio statale Pietro Mascagni';
update public.universities set name = 'Conservatorio di musica Luigi Boccherini'
 where erasmus_code = 'I LUCCA03' and name <> 'Conservatorio di musica Luigi Boccherini';
update public.universities set name = 'Conservatorio di Musica Lucio Campiani Mantova'
 where erasmus_code = 'I MANTOVA01' and name <> 'Conservatorio di Musica Lucio Campiani Mantova';
update public.universities set name = 'Conservatorio di Musica Egidio Romualdo Duni di Matera'
 where erasmus_code = 'I MATERA01' and name <> 'Conservatorio di Musica Egidio Romualdo Duni di Matera';
update public.universities set name = 'Conservatorio di Musica A. Corelli Messina'
 where erasmus_code = 'I MESSINA04' and name <> 'Conservatorio di Musica A. Corelli Messina';
update public.universities set name = 'Conservatorio di Musica G.verdi di Milano'
 where erasmus_code = 'I MILANO09' and name <> 'Conservatorio di Musica G.verdi di Milano';
update public.universities set name = 'Conservatorio di Musica Nino Rota'
 where erasmus_code = 'I MONOPOL02' and name <> 'Conservatorio di Musica Nino Rota';
update public.universities set name = 'Accademia di Belle Arti Pietro Vannucci'
 where erasmus_code = 'I PERUGIA04' and name <> 'Accademia di Belle Arti Pietro Vannucci';
update public.universities set name = 'Conservatorio Statale di Musica G.Rossini'
 where erasmus_code = 'I PESARO01' and name <> 'Conservatorio Statale di Musica G.Rossini';
update public.universities set name = 'Conservatorio di Musica Giuseppe Nicolini'
 where erasmus_code = 'I PIACENZ01' and name <> 'Conservatorio di Musica Giuseppe Nicolini';
update public.universities set name = 'Conservatorio di musica Gesualdo da Venosa'
 where erasmus_code = 'I POTENZA03' and name <> 'Conservatorio di musica Gesualdo da Venosa';
update public.universities set name = 'Istituto Superiore Di Studi Musicali Giuseppe Verdi'
 where erasmus_code = 'I RAVENNA02' and name <> 'Istituto Superiore Di Studi Musicali Giuseppe Verdi';
update public.universities set name = 'Conservatorio di Musica F. Cilea'
 where erasmus_code = 'I REGGIO03' and name <> 'Conservatorio di Musica F. Cilea';
update public.universities set name = 'Conservatorio di Musica Santa Cecilia'
 where erasmus_code = 'I ROMA09' and name <> 'Conservatorio di Musica Santa Cecilia';
update public.universities set name = 'Accademia Nazionale d''Arte Drammatica Silvio d''Amico'
 where erasmus_code = 'I ROMA29' and name <> 'Accademia Nazionale d''Arte Drammatica Silvio d''Amico';
update public.universities set name = 'DuofinArt srl'
 where erasmus_code = 'I ROMA39' and name <> 'DuofinArt srl';
update public.universities set name = 'Conservatorio Statale di Musica L. Canepa'
 where erasmus_code = 'I SASSARI02' and name <> 'Conservatorio Statale di Musica L. Canepa';
update public.universities set name = 'Accademia di Belle Arti Mario Sironi'
 where erasmus_code = 'I SASSARI03' and name <> 'Accademia di Belle Arti Mario Sironi';
update public.universities set name = 'Conservatorio di Siena Rinaldo Franci'
 where erasmus_code = 'I SIENA04' and name <> 'Conservatorio di Siena Rinaldo Franci';
update public.universities set name = 'I.T.S. GE. IN. LOGISTIC'
 where erasmus_code = 'I TARANTO01' and name <> 'I.T.S. GE. IN. LOGISTIC';
update public.universities set name = 'Istituto Statale Superiore di Studi Musicali e Coreutici G. Braga'
 where erasmus_code = 'I TERAMO02' and name <> 'Istituto Statale Superiore di Studi Musicali e Coreutici G. Braga';
update public.universities set name = 'Conservatorio Statale di Musica Giulio Briccialdi - Terni'
 where erasmus_code = 'I TERNI01' and name <> 'Conservatorio Statale di Musica Giulio Briccialdi - Terni';
update public.universities set name = 'Conservatorio Statale di Musica Giuseppe Verdi Torino'
 where erasmus_code = 'I TORINO05' and name <> 'Conservatorio Statale di Musica Giuseppe Verdi Torino';
update public.universities set name = 'Fondazione European School of Management Italia'
 where erasmus_code = 'I TORINO15' and name <> 'Fondazione European School of Management Italia';
update public.universities set name = 'Conservatorio di Musica di Stato Antonio Scontrino - Trapani'
 where erasmus_code = 'I TRAPANI02' and name <> 'Conservatorio di Musica di Stato Antonio Scontrino - Trapani';
update public.universities set name = 'Conservatorio di musica F.A. Bonporti di Trento'
 where erasmus_code = 'I TRENTO02' and name <> 'Conservatorio di musica F.A. Bonporti di Trento';
update public.universities set name = 'Conservatorio Statale di Musica Jacopo Tomadini'
 where erasmus_code = 'I UDINE02' and name <> 'Conservatorio Statale di Musica Jacopo Tomadini';
update public.universities set name = 'Fondazione Istituto Tecnologico Superiore - Academy Udine'
 where erasmus_code = 'I UDINE03' and name <> 'Fondazione Istituto Tecnologico Superiore - Academy Udine';
update public.universities set name = 'Fondazione Istituto Tecnico Superiore per la filiera dei trasporti e della logistica intermodale'
 where erasmus_code = 'I VARESE04' and name <> 'Fondazione Istituto Tecnico Superiore per la filiera dei trasporti e della logistica intermodale';
update public.universities set name = 'Universita Ca'' Foscari Venezia'
 where erasmus_code = 'I VENEZIA01' and name <> 'Universita Ca'' Foscari Venezia';
update public.universities set name = 'ITS MARCO POLO - Fondazione per la mobilità sostenibile nel sistema portuale e aeroportuale'
 where erasmus_code = 'I VENEZIA05' and name <> 'ITS MARCO POLO - Fondazione per la mobilità sostenibile nel sistema portuale e aeroportuale';
update public.universities set name = 'Conservatorio Statale di Musica E. F. Dall''Abaco'
 where erasmus_code = 'I VERONA02' and name <> 'Conservatorio Statale di Musica E. F. Dall''Abaco';
update public.universities set name = 'Fondazione di Partecipazione dell'' Istituto Tecnico Superiore Area Tecnologica della Mobilità Sostenibile - Logistica e Sistemi e Servizi Innovativi per la Mobilità di Persone e Merci'
 where erasmus_code = 'I VERONA04' and name <> 'Fondazione di Partecipazione dell'' Istituto Tecnico Superiore Area Tecnologica della Mobilità Sostenibile - Logistica e Sistemi e Servizi Innovativi per la Mobilità di Persone e Merci';
update public.universities set name = 'Conservatorio di Musica F.torrefranca Vibo Valentia'
 where erasmus_code = 'I VIBO VA01' and name <> 'Conservatorio di Musica F.torrefranca Vibo Valentia';
update public.universities set name = 'Conservatorio di Musica Arrigo Pedrollo di Vicenza'
 where erasmus_code = 'I VICENZA03' and name <> 'Conservatorio di Musica Arrigo Pedrollo di Vicenza';
update public.universities set name = 'University College Cork - National University of Ireland, Cork'
 where erasmus_code = 'IRLCORK01' and name <> 'University College Cork - National University of Ireland, Cork';
update public.universities set name = 'DU Agency DU Daugavpils medicinas koledza'
 where erasmus_code = 'LV DAUGAVP02' and name <> 'DU Agency DU Daugavpils medicinas koledza';
update public.universities set name = 'Faculty of Islamic Science Skopje'
 where erasmus_code = 'MK SKOPJE22' and name <> 'Faculty of Islamic Science Skopje';
update public.universities set name = 'Ss. Cyril and Methodius University in Skopje, Faculty of Orthodox Theology St. Clement of Ohrid in Skopje, accompanying member'
 where erasmus_code = 'MK SKOPJE24' and name <> 'Ss. Cyril and Methodius University in Skopje, Faculty of Orthodox Theology St. Clement of Ohrid in Skopje, accompanying member';
update public.universities set name = 'Cenil Centro de Línguas Lda / Isal'
 where erasmus_code = 'P FUNCHAL08' and name <> 'Cenil Centro de Línguas Lda / Isal';
update public.universities set name = 'Instituto Português de Administração de Marketing (Lisboa) - ENSILIS - Educação e Formação, Unipessoal LDA'
 where erasmus_code = 'P LISBOA110' and name <> 'Instituto Português de Administração de Marketing (Lisboa) - ENSILIS - Educação e Formação, Unipessoal LDA';
update public.universities set name = 'Espaço Atlântico Formação Financeira SA'
 where erasmus_code = 'P VILANOV07' and name <> 'Espaço Atlântico Formação Financeira SA';
update public.universities set name = 'Powszechna Wyzsza Szkola Humanistyczna Pomerania'
 where erasmus_code = 'PL CHOJNIC01' and name <> 'Powszechna Wyzsza Szkola Humanistyczna Pomerania';
update public.universities set name = 'Wyzsza Szkola Bezpieczenstwa Publicznego i Indywidualnego Apeiron w Krakowie'
 where erasmus_code = 'PL KRAKOW25' and name <> 'Wyzsza Szkola Bezpieczenstwa Publicznego i Indywidualnego Apeiron w Krakowie';
update public.universities set name = 'Wyzsza Szkola Przedsiebiorczoscii Administracji W Lublinie'
 where erasmus_code = 'PL LUBLIN06' and name <> 'Wyzsza Szkola Przedsiebiorczoscii Administracji W Lublinie';
update public.universities set name = 'Politechnika Rzeszowska Im Ignacego Lukasiewicza Prz'
 where erasmus_code = 'PL RZESZOW01' and name <> 'Politechnika Rzeszowska Im Ignacego Lukasiewicza Prz';
update public.universities set name = 'Akademia Wychowania Fizycznego Im.polskich Olimpijczykow We Wroclawi'
 where erasmus_code = 'PL WROCLAW08' and name <> 'Akademia Wychowania Fizycznego Im.polskich Olimpijczykow We Wroclawi';
update public.universities set name = 'Universitatea de Vest Vasile Goldis din Arad'
 where erasmus_code = 'RO ARAD02' and name <> 'Universitatea de Vest Vasile Goldis din Arad';
update public.universities set name = 'Academia Tehnica Militara Ferdinand I'
 where erasmus_code = 'RO BUCURES02' and name <> 'Academia Tehnica Militara Ferdinand I';
update public.universities set name = 'Universitatea Athenaeum din Bucuresti'
 where erasmus_code = 'RO BUCURES27' and name <> 'Universitatea Athenaeum din Bucuresti';
update public.universities set name = 'Artifex University of Bucharest'
 where erasmus_code = 'RO BUCURES42' and name <> 'Artifex University of Bucharest';
update public.universities set name = 'Universitatea Pentru Stiintele Vietii Ion Ionescu de la Brad Din Iasi'
 where erasmus_code = 'RO IASI03' and name <> 'Universitatea Pentru Stiintele Vietii Ion Ionescu de la Brad Din Iasi';
update public.universities set name = 'Universitatea APOLLONIA Din Iasi'
 where erasmus_code = 'RO IASI06' and name <> 'Universitatea APOLLONIA Din Iasi';
update public.universities set name = 'Universitatea de Medicina, Farmacie, Stiinte Si Tehnologie George Emil Palade Din Targu Mures'
 where erasmus_code = 'RO TARGU02' and name <> 'Universitatea de Medicina, Farmacie, Stiinte Si Tehnologie George Emil Palade Din Targu Mures';
update public.universities set name = 'Visoka medicinska skola strukovnih studija Milutin Milankovic'
 where erasmus_code = 'RS BELGRAD21' and name <> 'Visoka medicinska skola strukovnih studija Milutin Milankovic';
update public.universities set name = 'Visoka zdravstvena skola strukovnih studija Medika'
 where erasmus_code = 'RS BELGRAD26' and name <> 'Visoka zdravstvena skola strukovnih studija Medika';
update public.universities set name = 'Visoka skola Akademija za poslovnu ekonomiju Cacak'
 where erasmus_code = 'RS KRAGUJE06' and name <> 'Visoka skola Akademija za poslovnu ekonomiju Cacak';
update public.universities set name = 'Visoka poslovna skola strukovnih studija Prof. dr Radomir Bojkovic Krusevac'
 where erasmus_code = 'RS KRUSEVA03' and name <> 'Visoka poslovna skola strukovnih studija Prof. dr Radomir Bojkovic Krusevac';
update public.universities set name = 'Hogskolan i Halmstad'
 where erasmus_code = 'S HALMSTA01' and name <> 'Hogskolan i Halmstad';
update public.universities set name = 'Univerzita Konstantina Filozofa Vnitre'
 where erasmus_code = 'SK NITRA01' and name <> 'Univerzita Konstantina Filozofa Vnitre';
update public.universities set name = 'Universiteti i Shkencave Te Aplikuara Ne Ferizaj'
 where erasmus_code = 'XK FERIZAJ02' and name <> 'Universiteti i Shkencave Te Aplikuara Ne Ferizaj';
