-- 00037_universities_name_cleanup_2.sql
-- Second display-name tidy pass on the ECHE catalog (follows 00036):
--   * split a long name at a clear " - " / " / " / " | " separator (trade
--     name vs legal-form suffix, or bilingual native/English)
--   * curated names for Trinity College Dublin + University College Dublin,
--     whose comma-joined legal names no automated rule can safely shorten.
-- legal_name untouched (search). Idempotent per-row. 114 rows.

update public.universities set name = 'Private Pädagogische Hochschule'
 where erasmus_code = 'A INNSBRU09' and name <> 'Private Pädagogische Hochschule';
update public.universities set name = 'Umit Tirol'
 where erasmus_code = 'A INNSBRU20' and name <> 'Umit Tirol';
update public.universities set name = 'Paracelsus Medizinische Privatuniversitat Salzburg'
 where erasmus_code = 'A SALZBUR19' and name <> 'Paracelsus Medizinische Privatuniversitat Salzburg';
update public.universities set name = 'VMI - Vienna Music Institute'
 where erasmus_code = 'A WIEN74' and name <> 'VMI - Vienna Music Institute';
update public.universities set name = 'Patrimoine de L''ecole Royale Militaire'
 where erasmus_code = 'B BRUXEL01' and name <> 'Patrimoine de L''ecole Royale Militaire';
update public.universities set name = 'Institut supérieur de Promotion sociale Libre de Bruxelles'
 where erasmus_code = 'B BRUXEL94' and name <> 'Institut supérieur de Promotion sociale Libre de Bruxelles';
update public.universities set name = 'Centre de formation pour les secteurs infirmier et de santé de l''ACN'
 where erasmus_code = 'B BRUXEL97' and name <> 'Centre de formation pour les secteurs infirmier et de santé de l''ACN';
update public.universities set name = 'Académie Royale des Beaux-Arts de Liege'
 where erasmus_code = 'B LIEGE02' and name <> 'Académie Royale des Beaux-Arts de Liege';
update public.universities set name = 'Academia Rerum Civilium'
 where erasmus_code = 'CZ KOLIN01' and name <> 'Academia Rerum Civilium';
update public.universities set name = 'Hochschule Fur Angewandte Wissenschaften'
 where erasmus_code = 'D ANSBACH01' and name <> 'Hochschule Fur Angewandte Wissenschaften';
update public.universities set name = 'VICTORIA'
 where erasmus_code = 'D BERLIN40' and name <> 'VICTORIA';
update public.universities set name = 'Hochschule Bielefeld'
 where erasmus_code = 'D BIELEFE02' and name <> 'Hochschule Bielefeld';
update public.universities set name = 'Fachhochschule des Mittelstandes (Fhm) Gmbh'
 where erasmus_code = 'D BIELEFE05' and name <> 'Fachhochschule des Mittelstandes (Fhm) Gmbh';
update public.universities set name = 'ISM International School of Management GmbH'
 where erasmus_code = 'D DORTMUN04' and name <> 'ISM International School of Management GmbH';
update public.universities set name = 'Bucerius Law School'
 where erasmus_code = 'D HAMBURG10' and name <> 'Bucerius Law School';
update public.universities set name = 'Hochschule fuer Grafik und Buchkunst Leipzig'
 where erasmus_code = 'D LEIPZIG04' and name <> 'Hochschule fuer Grafik und Buchkunst Leipzig';
update public.universities set name = 'Fremdspracheninstitut LHM'
 where erasmus_code = 'D MUNCHEN13' and name <> 'Fremdspracheninstitut LHM';
update public.universities set name = 'Technische Hochschule Rosenheim'
 where erasmus_code = 'D ROSENHE01' and name <> 'Technische Hochschule Rosenheim';
update public.universities set name = 'media Akademie'
 where erasmus_code = 'D STUTTGA14' and name <> 'media Akademie';
update public.universities set name = 'Syddansk Musikkonservatorium'
 where erasmus_code = 'DK ODENSE22' and name <> 'Syddansk Musikkonservatorium';
update public.universities set name = 'Centro Integrado de Formación Profesional de Ávila'
 where erasmus_code = 'E AVILA06' and name <> 'Centro Integrado de Formación Profesional de Ávila';
update public.universities set name = 'Consorci Mar Parc de Salut de Barcelona'
 where erasmus_code = 'E BARCELO66' and name <> 'Consorci Mar Parc de Salut de Barcelona';
update public.universities set name = 'Arzobispado de Granada'
 where erasmus_code = 'E GRANADA51' and name <> 'Arzobispado de Granada';
update public.universities set name = 'Congregacion de Los Hermanos de Las Escuelas Cristianas'
 where erasmus_code = 'E LLEIDA14' and name <> 'Congregacion de Los Hermanos de Las Escuelas Cristianas';
update public.universities set name = 'Congregación de Los Hermanos de Las Escuelas Cristianas'
 where erasmus_code = 'E LLEIDA16' and name <> 'Congregación de Los Hermanos de Las Escuelas Cristianas';
update public.universities set name = 'Institución La Salle'
 where erasmus_code = 'E MADRID235' and name <> 'Institución La Salle';
update public.universities set name = 'Centro Profesional Europeo de Madrid'
 where erasmus_code = 'E MADRID243' and name <> 'Centro Profesional Europeo de Madrid';
update public.universities set name = 'Centro Profesional Europeo de Madrid'
 where erasmus_code = 'E MADRID248' and name <> 'Centro Profesional Europeo de Madrid';
update public.universities set name = 'Fundació Per Als Estudis de Música i Arts Escèniques de les Illes Balears'
 where erasmus_code = 'E PALMA25' and name <> 'Fundació Per Als Estudis de Música i Arts Escèniques de les Illes Balears';
update public.universities set name = 'Fundació per als Estudis Superiors de Música i Arts Escèniques de les Illes Balears'
 where erasmus_code = 'E PALMA27' and name <> 'Fundació per als Estudis Superiors de Música i Arts Escèniques de les Illes Balears';
update public.universities set name = 'Fundación Educativa Jesuitas Centro Este'
 where erasmus_code = 'E PALMA34' and name <> 'Fundación Educativa Jesuitas Centro Este';
update public.universities set name = 'Centro Integrado Escuela Sanitaria Técnico Profesional de Navarra'
 where erasmus_code = 'E PAMPLON10' and name <> 'Centro Integrado Escuela Sanitaria Técnico Profesional de Navarra';
update public.universities set name = 'Centro Integrado Escuela de Educadoras y Educadores'
 where erasmus_code = 'E PAMPLON22' and name <> 'Centro Integrado Escuela de Educadoras y Educadores';
update public.universities set name = 'Escuela Superior de Conservación y Restauración de Bienes Culturales de Galicia'
 where erasmus_code = 'E PONTEVE08' and name <> 'Escuela Superior de Conservación y Restauración de Bienes Culturales de Galicia';
update public.universities set name = 'Escuelas Profesionales de la Sagrada Familia'
 where erasmus_code = 'E SEVILLA34' and name <> 'Escuelas Profesionales de la Sagrada Familia';
update public.universities set name = 'Instituto de Enseñanza Secundaria Puerto de la Cruz'
 where erasmus_code = 'E TENERIF04' and name <> 'Instituto de Enseñanza Secundaria Puerto de la Cruz';
update public.universities set name = 'Fundacion Universitaria San Pablo-ceu'
 where erasmus_code = 'E VALENCI08' and name <> 'Fundacion Universitaria San Pablo-ceu';
update public.universities set name = 'Universitat Internacional Valenciana'
 where erasmus_code = 'E VALENCI104' and name <> 'Universitat Internacional Valenciana';
update public.universities set name = 'Asociacion Casa de la Beneficencia'
 where erasmus_code = 'E VALLADO36' and name <> 'Asociacion Casa de la Beneficencia';
update public.universities set name = 'Mediterranean Agronomic Institute of Zaragoza'
 where erasmus_code = 'E ZARAGOZ23' and name <> 'Mediterranean Agronomic Institute of Zaragoza';
update public.universities set name = 'Etablissement public local Enseignement Formation Professionnelle Agricoles TARN'
 where erasmus_code = 'F ALBI06' and name <> 'Etablissement public local Enseignement Formation Professionnelle Agricoles TARN';
update public.universities set name = 'I.s.b.a.'
 where erasmus_code = 'F BESANCO14' and name <> 'I.s.b.a.';
update public.universities set name = 'Lycée des métiers de l''hôtellerie et du tourisme'
 where erasmus_code = 'F BLOIS02' and name <> 'Lycée des métiers de l''hôtellerie et du tourisme';
update public.universities set name = 'Centre Hospitalier de Brive'
 where erasmus_code = 'F BRIVE06' and name <> 'Centre Hospitalier de Brive';
update public.universities set name = 'Institut Régional de Développement du Travail Social'
 where erasmus_code = 'F CAYENNE08' and name <> 'Institut Régional de Développement du Travail Social';
update public.universities set name = 'Etablissement Public Local d''Enseignement et de Formation Professionnelle Agricoles de Chambery'
 where erasmus_code = 'F CHAMBER18' and name <> 'Etablissement Public Local d''Enseignement et de Formation Professionnelle Agricoles de Chambery';
update public.universities set name = 'Lycee Professionnel Bertene Juminer'
 where erasmus_code = 'F FORT FR24' and name <> 'Lycee Professionnel Bertene Juminer';
update public.universities set name = 'association andré coindre (ensemble scolaire Saint Pierre'
 where erasmus_code = 'F LANGOGN01' and name <> 'association andré coindre (ensemble scolaire Saint Pierre';
update public.universities set name = 'Promotrans'
 where erasmus_code = 'F LILLE75' and name <> 'Promotrans';
update public.universities set name = 'Groupe scolaire Saint-Louis'
 where erasmus_code = 'F LORIENT11' and name <> 'Groupe scolaire Saint-Louis';
update public.universities set name = 'Institut de Formation des Professionnels de Sante'
 where erasmus_code = 'F LORIENT12' and name <> 'Institut de Formation des Professionnels de Sante';
update public.universities set name = 'EKLYA School of Business'
 where erasmus_code = 'F LYON126' and name <> 'EKLYA School of Business';
update public.universities set name = 'Ecole d''Infirmières et d''Assistantes de Service Social de Lyon'
 where erasmus_code = 'F LYON139' and name <> 'Ecole d''Infirmières et d''Assistantes de Service Social de Lyon';
update public.universities set name = 'Croix-rouge Francaise'
 where erasmus_code = 'F LYON43' and name <> 'Croix-rouge Francaise';
update public.universities set name = 'Lycee Professionnel Jean-baptiste Brochier'
 where erasmus_code = 'F MARSEIL97' and name <> 'Lycee Professionnel Jean-baptiste Brochier';
update public.universities set name = 'Centre Hospitalier de Millau'
 where erasmus_code = 'F MILLAU02' and name <> 'Centre Hospitalier de Millau';
update public.universities set name = 'Centre international des Hautes Etudes Agronomiques Méditerranéennes'
 where erasmus_code = 'F MONTPEL30' and name <> 'Centre international des Hautes Etudes Agronomiques Méditerranéennes';
update public.universities set name = 'Lycée des métiers de la création graphisme et numérique'
 where erasmus_code = 'F MONTREU02' and name <> 'Lycée des métiers de la création graphisme et numérique';
update public.universities set name = 'Centre Hospitalier Intercommunal de l''Ouest Vosgien'
 where erasmus_code = 'F NEUFCHA02' and name <> 'Centre Hospitalier Intercommunal de l''Ouest Vosgien';
update public.universities set name = 'Institut National des Sciences Et Industries du Vivant Et de L''environnement'
 where erasmus_code = 'F PARIS077' and name <> 'Institut National des Sciences Et Industries du Vivant Et de L''environnement';
update public.universities set name = 'Lycee Jean Lurcat'
 where erasmus_code = 'F PARIS354' and name <> 'Lycee Jean Lurcat';
update public.universities set name = 'Pôle supérieur d''enseignement artistique Paris'
 where erasmus_code = 'F PARIS365' and name <> 'Pôle supérieur d''enseignement artistique Paris';
update public.universities set name = 'Lycée d''Enseignement Privé Agricole'
 where erasmus_code = 'F PARIS405' and name <> 'Lycée d''Enseignement Privé Agricole';
update public.universities set name = 'Lycée technologique'
 where erasmus_code = 'F ROUBAIX09' and name <> 'Lycée technologique';
update public.universities set name = 'Institut Formation Soins Infirmiers'
 where erasmus_code = 'F SARCELL01' and name <> 'Institut Formation Soins Infirmiers';
update public.universities set name = 'Association pour la Formation en Milieu Rural'
 where erasmus_code = 'F ST PALA02' and name <> 'Association pour la Formation en Milieu Rural';
update public.universities set name = 'Centre Hospitalier Tarbes-Lourdes'
 where erasmus_code = 'F TARBES11' and name <> 'Centre Hospitalier Tarbes-Lourdes';
update public.universities set name = 'Promotrans'
 where erasmus_code = 'F TOULOUS63' and name <> 'Promotrans';
update public.universities set name = 'Ecole Supérieure de Vente et de Management'
 where erasmus_code = 'F VERSAIL15' and name <> 'Ecole Supérieure de Vente et de Management';
update public.universities set name = 'Athens University of Economics and Business'
 where erasmus_code = 'G ATHINE04' and name <> 'Athens University of Economics and Business';
update public.universities set name = 'Istarsko Veleuciliste'
 where erasmus_code = 'HR PULA02' and name <> 'Istarsko Veleuciliste';
update public.universities set name = 'Scuola Superiore per Mediatori Linguistici'
 where erasmus_code = 'I BENEVEN05' and name <> 'Scuola Superiore per Mediatori Linguistici';
update public.universities set name = 'Fondazione Istituto Tecnico Superiore per le nuove tecnologie per il made in Italy'
 where erasmus_code = 'I BERGAMO05' and name <> 'Fondazione Istituto Tecnico Superiore per le nuove tecnologie per il made in Italy';
update public.universities set name = 'Fondazione Istituto Tecnico Superiore Per le Nuove Tecnologie Per Il Made in Italy Sistema Moda'
 where erasmus_code = 'I BIELLA01' and name <> 'Fondazione Istituto Tecnico Superiore Per le Nuove Tecnologie Per Il Made in Italy Sistema Moda';
update public.universities set name = 'Vincenzo Foppa Società Cooperativa Sociale'
 where erasmus_code = 'I BRESCIA04' and name <> 'Vincenzo Foppa Società Cooperativa Sociale';
update public.universities set name = 'Instituto Superiore di Stdudi Musicali'
 where erasmus_code = 'I CUNEO01' and name <> 'Instituto Superiore di Stdudi Musicali';
update public.universities set name = 'Fondazione ITS Academy'
 where erasmus_code = 'I GENOVA07' and name <> 'Fondazione ITS Academy';
update public.universities set name = 'Fondazione Istituto Tecnico Superiore per l''Agroalimentare Sostenibile'
 where erasmus_code = 'I MANTOVA03' and name <> 'Fondazione Istituto Tecnico Superiore per l''Agroalimentare Sostenibile';
update public.universities set name = 'Scuola Superiore per Mediatori Linguistici Nelson Mandela e Istituto del Design'
 where erasmus_code = 'I MATERA02' and name <> 'Scuola Superiore per Mediatori Linguistici Nelson Mandela e Istituto del Design';
update public.universities set name = 'Ied Istituto Europeo di Design Societa'' Per Azioni'
 where erasmus_code = 'I MILANO18' and name <> 'Ied Istituto Europeo di Design Societa'' Per Azioni';
update public.universities set name = 'Istituto tecnico superiore per le tecnologie innovative per i beni e le attività culturali'
 where erasmus_code = 'I MILANO32' and name <> 'Istituto tecnico superiore per le tecnologie innovative per i beni e le attività culturali';
update public.universities set name = 'I-CREA Academy'
 where erasmus_code = 'I MILANO33' and name <> 'I-CREA Academy';
update public.universities set name = 'Istituto Tecnico Superiore'
 where erasmus_code = 'I PARMA03' and name <> 'Istituto Tecnico Superiore';
update public.universities set name = 'Istituto Tecnico Superiore Per le Tecnologie Innovative Per i Beni e le Attivita'' Culturali'
 where erasmus_code = 'I PESARO02' and name <> 'Istituto Tecnico Superiore Per le Tecnologie Innovative Per i Beni e le Attivita'' Culturali';
update public.universities set name = 'Unicamillus'
 where erasmus_code = 'I ROMA40' and name <> 'Unicamillus';
update public.universities set name = 'Fondazione Its'
 where erasmus_code = 'I TERAMO03' and name <> 'Fondazione Its';
update public.universities set name = 'Istituto Tecnico Superiore Tecnologie dell''Informazione e della Comunicazione Sardegna'
 where erasmus_code = 'I TORTOL01' and name <> 'Istituto Tecnico Superiore Tecnologie dell''Informazione e della Comunicazione Sardegna';
update public.universities set name = 'Conservatorio di Musica di Stato Antonio Scontrino'
 where erasmus_code = 'I TRAPANI02' and name <> 'Conservatorio di Musica di Stato Antonio Scontrino';
update public.universities set name = 'Istituto Tecnologico Superiore per la chimica e le nuove tecnologie della vita'
 where erasmus_code = 'I TRIESTE05' and name <> 'Istituto Tecnologico Superiore per la chimica e le nuove tecnologie della vita';
update public.universities set name = 'ITS MARCO POLO'
 where erasmus_code = 'I VENEZIA05' and name <> 'ITS MARCO POLO';
update public.universities set name = 'Fondazione di Partecipazione dell'' Istituto Tecnico Superiore Area Tecnologica della Mobilità Sostenibile'
 where erasmus_code = 'I VERONA04' and name <> 'Fondazione di Partecipazione dell'' Istituto Tecnico Superiore Area Tecnologica della Mobilità Sostenibile';
update public.universities set name = 'University College Cork'
 where erasmus_code = 'IRLCORK01' and name <> 'University College Cork';
update public.universities set name = 'Trinity College Dublin'
 where erasmus_code = 'IRLDUBLIN01' and name <> 'Trinity College Dublin';
update public.universities set name = 'University College Dublin'
 where erasmus_code = 'IRLDUBLIN02' and name <> 'University College Dublin';
update public.universities set name = 'École de Commerce et de Gestion'
 where erasmus_code = 'LUXLUX VIL07' and name <> 'École de Commerce et de Gestion';
update public.universities set name = 'Republic of Macedonia'
 where erasmus_code = 'MK OHRID01' and name <> 'Republic of Macedonia';
update public.universities set name = 'Private Higher Education Institution'
 where erasmus_code = 'MK SKOPJE10' and name <> 'Private Higher Education Institution';
update public.universities set name = 'Private independent higher institution Higher professional school Business Academy Smilevski'
 where erasmus_code = 'MK SKOPJE12' and name <> 'Private independent higher institution Higher professional school Business Academy Smilevski';
update public.universities set name = 'Republika Makedonija Univerzitet Goce Delchev Shtip'
 where erasmus_code = 'MK SKOPJE20' and name <> 'Republika Makedonija Univerzitet Goce Delchev Shtip';
update public.universities set name = 'Instituto Português de Administração de Marketing (Lisboa)'
 where erasmus_code = 'P LISBOA110' and name <> 'Instituto Português de Administração de Marketing (Lisboa)';
update public.universities set name = 'Universidade Lusíada'
 where erasmus_code = 'P LISBOA12' and name <> 'Universidade Lusíada';
update public.universities set name = 'Instituto Português de Administração de Marketing (Porto) ENSILIS'
 where erasmus_code = 'P PORTO29' and name <> 'Instituto Português de Administração de Marketing (Porto) ENSILIS';
update public.universities set name = 'FACULTAS, SA entidade instituidora do ISCET'
 where erasmus_code = 'P PORTO42' and name <> 'FACULTAS, SA entidade instituidora do ISCET';
update public.universities set name = 'Instytut Maszyn Przeplywowych Im Roberta Szewalskiego Polskiej Akademii Nauk'
 where erasmus_code = 'PL GDANSK14' and name <> 'Instytut Maszyn Przeplywowych Im Roberta Szewalskiego Polskiej Akademii Nauk';
update public.universities set name = 'Instytut Mechaniki Gorotworu'
 where erasmus_code = 'PL KRAKOW32' and name <> 'Instytut Mechaniki Gorotworu';
update public.universities set name = 'Wyzsza Szkola Biznesu'
 where erasmus_code = 'PL NOWY SA01' and name <> 'Wyzsza Szkola Biznesu';
update public.universities set name = 'Akademia Nauk Stosowanych'
 where erasmus_code = 'PL OPOLE05' and name <> 'Akademia Nauk Stosowanych';
update public.universities set name = 'Papieski Wydzial Teologiczny W Warszawie Sekcja Sw. Andrzeja Boboli'
 where erasmus_code = 'PL WARSZAW66' and name <> 'Papieski Wydzial Teologiczny W Warszawie Sekcja Sw. Andrzeja Boboli';
update public.universities set name = 'Visoka strukovna skola'
 where erasmus_code = 'RS BELGRAD29' and name <> 'Visoka strukovna skola';
update public.universities set name = 'Visoka Skola Strukovnih Studija'
 where erasmus_code = 'RS NOVISAD05' and name <> 'Visoka Skola Strukovnih Studija';
update public.universities set name = 'Oulun Ammattikorkeakoulu Oy'
 where erasmus_code = 'SF OULU11' and name <> 'Oulun Ammattikorkeakoulu Oy';
update public.universities set name = 'Gea College Cvs Druzba Za Visjesolsko Izobrazevanje'
 where erasmus_code = 'SI LJUBLJA07' and name <> 'Gea College Cvs Druzba Za Visjesolsko Izobrazevanje';
update public.universities set name = 'VSR - Visoka sola za racunovodstvo in finance, Ljubljana'
 where erasmus_code = 'SI LJUBLJA28' and name <> 'VSR - Visoka sola za racunovodstvo in finance, Ljubljana';
update public.universities set name = 'Hudobna a Umelecka Akademia Jana Albrechta'
 where erasmus_code = 'SK BANSK S01' and name <> 'Hudobna a Umelecka Akademia Jana Albrechta';
