-- 00041_universities_acronym_casing.sql
-- Restore 49 initialisms the title-caser had lower-cased (ESSCA, CEU, IMEP, …).
-- Pronounceable brands stored all-caps by the source (Odisee, Audencia, …) are
-- intentionally left title-cased. legal_name untouched. Idempotent. 49 rows.

update public.universities set name = 'CEU'
 where erasmus_code = 'A WIEN78' and name <> 'CEU';
update public.universities set name = 'IMEP'
 where erasmus_code = 'B NAMUR13' and name <> 'IMEP';
update public.universities set name = 'AUB'
 where erasmus_code = 'CY NICOSIA40' and name <> 'AUB';
update public.universities set name = 'CIFASA'
 where erasmus_code = 'E CIUDA R18' and name <> 'CIFASA';
update public.universities set name = 'CESINEC'
 where erasmus_code = 'E SANTAND35' and name <> 'CESINEC';
update public.universities set name = 'CEPA'
 where erasmus_code = 'E SEVILLA94' and name <> 'CEPA';
update public.universities set name = 'OGESSCA'
 where erasmus_code = 'F AMIENS30' and name <> 'OGESSCA';
update public.universities set name = 'ESSCA'
 where erasmus_code = 'F ANGERS10' and name <> 'ESSCA';
update public.universities set name = 'IPAC'
 where erasmus_code = 'F ANNECY04' and name <> 'IPAC';
update public.universities set name = 'GARAC'
 where erasmus_code = 'F ARGENT08' and name <> 'GARAC';
update public.universities set name = 'CFPTS'
 where erasmus_code = 'F BAGNOLET03' and name <> 'CFPTS';
update public.universities set name = 'ICFA'
 where erasmus_code = 'F BORDEAU68' and name <> 'ICFA';
update public.universities set name = 'ESTACOM'
 where erasmus_code = 'F BOURGES13' and name <> 'ESTACOM';
update public.universities set name = 'CIFEP'
 where erasmus_code = 'F CHAMBER14' and name <> 'CIFEP';
update public.universities set name = 'LÉA-CFI'
 where erasmus_code = 'F CRETEIL14' and name <> 'LÉA-CFI';
update public.universities set name = 'IRFASE'
 where erasmus_code = 'F EVRY13' and name <> 'IRFASE';
update public.universities set name = 'AMEP'
 where erasmus_code = 'F FORT FR10' and name <> 'AMEP';
update public.universities set name = 'ICSSA'
 where erasmus_code = 'F LA ROCH12' and name <> 'ICSSA';
update public.universities set name = 'CIPECMA'
 where erasmus_code = 'F LA ROCH18' and name <> 'CIPECMA';
update public.universities set name = 'OGICES'
 where erasmus_code = 'F LAROCHE01' and name <> 'OGICES';
update public.universities set name = 'ESTS'
 where erasmus_code = 'F LILLE45' and name <> 'ESTS';
update public.universities set name = 'ARFRIPS'
 where erasmus_code = 'F LYON127' and name <> 'ARFRIPS';
update public.universities set name = 'ECEMA'
 where erasmus_code = 'F LYON135' and name <> 'ECEMA';
update public.universities set name = 'ISARA'
 where erasmus_code = 'F LYON17' and name <> 'ISARA';
update public.universities set name = 'MBS'
 where erasmus_code = 'F MONTPEL13' and name <> 'MBS';
update public.universities set name = 'ENSEC'
 where erasmus_code = 'F NANTES24' and name <> 'ENSEC';
update public.universities set name = 'GIPAFOC'
 where erasmus_code = 'F NANTES96' and name <> 'GIPAFOC';
update public.universities set name = 'ISIM'
 where erasmus_code = 'F NICE46' and name <> 'ISIM';
update public.universities set name = 'ESTP'
 where erasmus_code = 'F PARIS068' and name <> 'ESTP';
update public.universities set name = 'ETSUP'
 where erasmus_code = 'F PARIS160' and name <> 'ETSUP';
update public.universities set name = 'CESI'
 where erasmus_code = 'F PARIS335' and name <> 'CESI';
update public.universities set name = 'IDAA'
 where erasmus_code = 'F PARIS373' and name <> 'IDAA';
update public.universities set name = 'CQFD'
 where erasmus_code = 'F PARIS383' and name <> 'CQFD';
update public.universities set name = 'ESMOD'
 where erasmus_code = 'F PARIS413' and name <> 'ESMOD';
update public.universities set name = 'ILERI'
 where erasmus_code = 'F PARIS429' and name <> 'ILERI';
update public.universities set name = 'ISIMI'
 where erasmus_code = 'F PARIS431' and name <> 'ISIMI';
update public.universities set name = 'ISEM'
 where erasmus_code = 'F PARIS432' and name <> 'ISEM';
update public.universities set name = 'DDLM'
 where erasmus_code = 'F PARIS463' and name <> 'DDLM';
update public.universities set name = 'CNPC-CFA'
 where erasmus_code = 'F PAU18' and name <> 'CNPC-CFA';
update public.universities set name = 'ECPM'
 where erasmus_code = 'F PERPIGN23' and name <> 'ECPM';
update public.universities set name = 'ESIGELEC'
 where erasmus_code = 'F ROUEN07' and name <> 'ESIGELEC';
update public.universities set name = 'ADSCI'
 where erasmus_code = 'F ROUEN28' and name <> 'ADSCI';
update public.universities set name = 'ISTP'
 where erasmus_code = 'F ST ETIE34' and name <> 'ISTP';
update public.universities set name = 'ORT'
 where erasmus_code = 'F STRASBO52' and name <> 'ORT';
update public.universities set name = 'ENSAV'
 where erasmus_code = 'F VERSAIL05' and name <> 'ENSAV';
update public.universities set name = 'ISIPCA'
 where erasmus_code = 'F VERSAIL22' and name <> 'ISIPCA';
update public.universities set name = 'LABA'
 where erasmus_code = 'I BRESCIA05' and name <> 'LABA';
update public.universities set name = 'FUSP'
 where erasmus_code = 'I FORLI01' and name <> 'FUSP';
update public.universities set name = 'AEA'
 where erasmus_code = 'MT MALTA08' and name <> 'AEA';
