-- 00040_universities_name_cleanup_3.sql
-- Bulk display-name cleanup pass over the ECHE catalog (legal_name untouched):
--   * strip trailing corporate/legal forms (GmbH, Srl, Ltd, Oy, s.r.o.,
--     S.L.U., vzw, o.p.s., gemeinnützige, …) — never a parenthetical acronym
--   * uppercase dotted initialisms (I.e.s. -> I.E.S., C.i.f.p. -> C.I.F.P.)
--   * title-case names that were all-caps once their legal form was removed
--   * drop separator/quote-split artifacts (dangling " -", unclosed "(")
-- Idempotent per-row. 382 rows.

update public.universities set name = 'Fachhochschule Vorarlberg'
 where erasmus_code = 'A DORNBIR01' and name <> 'Fachhochschule Vorarlberg';
update public.universities set name = 'Hochschule Fur Angewandte Wissenschaften Burgenland'
 where erasmus_code = 'A EISENST02' and name <> 'Hochschule Fur Angewandte Wissenschaften Burgenland';
update public.universities set name = 'Joseph Haydn Privathochschule'
 where erasmus_code = 'A EISENST05' and name <> 'Joseph Haydn Privathochschule';
update public.universities set name = 'Stella Vorarlberg Privathochschule für Musik'
 where erasmus_code = 'A FELDKIR03' and name <> 'Stella Vorarlberg Privathochschule für Musik';
update public.universities set name = 'Fh Joanneum'
 where erasmus_code = 'A GRAZ09' and name <> 'Fh Joanneum';
update public.universities set name = 'Campus 02 Fachhochschule der Wirtschaft'
 where erasmus_code = 'A GRAZ10' and name <> 'Campus 02 Fachhochschule der Wirtschaft';
update public.universities set name = 'Mci Management Center Innsbruck Internationale Hochschule'
 where erasmus_code = 'A INNSBRU08' and name <> 'Mci Management Center Innsbruck Internationale Hochschule';
update public.universities set name = 'Fhg - Zentrum Fuer Gesundheitsberufe Tirol'
 where erasmus_code = 'A INNSBRU23' and name <> 'Fhg - Zentrum Fuer Gesundheitsberufe Tirol';
update public.universities set name = 'Imc Hochschule Fur Angewandte Wissenschaften Krems'
 where erasmus_code = 'A KREMS03' and name <> 'Imc Hochschule Fur Angewandte Wissenschaften Krems';
update public.universities set name = 'Karl Landsteiner Privatuniversitat Fur Gesundheitswissenschaften'
 where erasmus_code = 'A KREMS06' and name <> 'Karl Landsteiner Privatuniversitat Fur Gesundheitswissenschaften';
update public.universities set name = 'Danube Private University'
 where erasmus_code = 'A KREMS07' and name <> 'Danube Private University';
update public.universities set name = 'Fachhochschule Kufstein Tirol Bildungs'
 where erasmus_code = 'A KUFSTEI01' and name <> 'Fachhochschule Kufstein Tirol Bildungs';
update public.universities set name = 'FH Gesundheitsberufe OÖ'
 where erasmus_code = 'A LINZ23' and name <> 'FH Gesundheitsberufe OÖ';
update public.universities set name = 'Fachhochschule Salzburg'
 where erasmus_code = 'A SALZBUR08' and name <> 'Fachhochschule Salzburg';
update public.universities set name = 'Privatuniversitat Schloss Seeburg'
 where erasmus_code = 'A SALZBUR18' and name <> 'Privatuniversitat Schloss Seeburg';
update public.universities set name = 'Fh Kaernten - Gemeinnuetzige'
 where erasmus_code = 'A SPITTAL01' and name <> 'Fh Kaernten - Gemeinnuetzige';
update public.universities set name = 'Hochschule für Angewandte Wissenschaften St. Pölten'
 where erasmus_code = 'A ST POLT03' and name <> 'Hochschule für Angewandte Wissenschaften St. Pölten';
update public.universities set name = 'New Design University Privatuniversitat'
 where erasmus_code = 'A ST POLT10' and name <> 'New Design University Privatuniversitat';
update public.universities set name = 'Bertha von Suttner Privatuniversität St. Pölten'
 where erasmus_code = 'A ST POLT11' and name <> 'Bertha von Suttner Privatuniversität St. Pölten';
update public.universities set name = 'Fh Oo Studienbetriebs'
 where erasmus_code = 'A WELS01' and name <> 'Fh Oo Studienbetriebs';
update public.universities set name = 'Fhw Fachhochschul-studiengange Betriebs Und Forschungseinrichtungen der Wiener Wirtschaft'
 where erasmus_code = 'A WIEN21' and name <> 'Fhw Fachhochschul-studiengange Betriebs Und Forschungseinrichtungen der Wiener Wirtschaft';
update public.universities set name = 'Fachhochschule des Bfi Wien'
 where erasmus_code = 'A WIEN38' and name <> 'Fachhochschule des Bfi Wien';
update public.universities set name = 'Musik und Kunst Privatuniversität der Stadt Wien'
 where erasmus_code = 'A WIEN52' and name <> 'Musik und Kunst Privatuniversität der Stadt Wien';
update public.universities set name = 'Modul University Vienna'
 where erasmus_code = 'A WIEN66' and name <> 'Modul University Vienna';
update public.universities set name = 'Sigmund Freud Privatuniversitat Wien'
 where erasmus_code = 'A WIEN68' and name <> 'Sigmund Freud Privatuniversitat Wien';
update public.universities set name = 'Ceu'
 where erasmus_code = 'A WIEN78' and name <> 'Ceu';
update public.universities set name = 'COGNOS Education'
 where erasmus_code = 'A WIEN79' and name <> 'COGNOS Education';
update public.universities set name = 'Fachhochschule Wiener Neustadt'
 where erasmus_code = 'A WIENER01' and name <> 'Fachhochschule Wiener Neustadt';
update public.universities set name = 'Ferdinand Porsche Fernfachhochschule'
 where erasmus_code = 'A WIENER05' and name <> 'Ferdinand Porsche Fernfachhochschule';
update public.universities set name = 'Thomas More Kempen'
 where erasmus_code = 'B GEEL07' and name <> 'Thomas More Kempen';
update public.universities set name = 'Orpheus Instituut'
 where erasmus_code = 'B GENT40' and name <> 'Orpheus Instituut';
update public.universities set name = 'Lenia Educational Centre'
 where erasmus_code = 'CY AMMOCH01' and name <> 'Lenia Educational Centre';
update public.universities set name = 'P.A. College'
 where erasmus_code = 'CY LARNACA01' and name <> 'P.A. College';
update public.universities set name = 'Uclan Cyprus'
 where erasmus_code = 'CY LARNACA02' and name <> 'Uclan Cyprus';
update public.universities set name = 'Mc Mesoyios College'
 where erasmus_code = 'CY LIMASSO04' and name <> 'Mc Mesoyios College';
update public.universities set name = 'Chrysako Educational Centre'
 where erasmus_code = 'CY NICOSIA10' and name <> 'Chrysako Educational Centre';
update public.universities set name = 'Scholai Frederickou'
 where erasmus_code = 'CY NICOSIA13' and name <> 'Scholai Frederickou';
update public.universities set name = 'Edex - Educational Excellence Corporation'
 where erasmus_code = 'CY NICOSIA14' and name <> 'Edex - Educational Excellence Corporation';
update public.universities set name = 'European University - Cyprus'
 where erasmus_code = 'CY NICOSIA24' and name <> 'European University - Cyprus';
update public.universities set name = 'Ekpedeftiria Kes'
 where erasmus_code = 'CY NICOSIA25' and name <> 'Ekpedeftiria Kes';
update public.universities set name = 'Eimf Holding'
 where erasmus_code = 'CY NICOSIA39' and name <> 'Eimf Holding';
update public.universities set name = 'Aub'
 where erasmus_code = 'CY NICOSIA40' and name <> 'Aub';
update public.universities set name = 'Global College'
 where erasmus_code = 'CY NICOSIA41' and name <> 'Global College';
update public.universities set name = 'Hellenic College of Music Pitsa Spyridaki & Company'
 where erasmus_code = 'CY NICOSIA42' and name <> 'Hellenic College of Music Pitsa Spyridaki & Company';
update public.universities set name = 'C.D.A. College Pafos'
 where erasmus_code = 'CY PAFOS02' and name <> 'C.D.A. College Pafos';
update public.universities set name = 'Vysoka Skola Newton'
 where erasmus_code = 'CZ BRNO08' and name <> 'Vysoka Skola Newton';
update public.universities set name = 'Vysoka skola obchodni a hotelova'
 where erasmus_code = 'CZ BRNO12' and name <> 'Vysoka skola obchodni a hotelova';
update public.universities set name = 'Akademie Sting'
 where erasmus_code = 'CZ BRNO14' and name <> 'Akademie Sting';
update public.universities set name = 'Vysoka skola evropskych a regionalnich studii'
 where erasmus_code = 'CZ CESKE03' and name <> 'Vysoka skola evropskych a regionalnich studii';
update public.universities set name = 'Soukroma Vyssi Odborna Skola Socialni'
 where erasmus_code = 'CZ JIHLAVA03' and name <> 'Soukroma Vyssi Odborna Skola Socialni';
update public.universities set name = 'Skoda Auto Vysoka Skola'
 where erasmus_code = 'CZ MLADA01' and name <> 'Skoda Auto Vysoka Skola';
update public.universities set name = 'Moravska Vysoka Skola Olomouc'
 where erasmus_code = 'CZ OLOMOUC03' and name <> 'Moravska Vysoka Skola Olomouc';
update public.universities set name = 'Evropská výzkumná univerzita'
 where erasmus_code = 'CZ OSTRAVA03' and name <> 'Evropská výzkumná univerzita';
update public.universities set name = 'EUROPEAN COLLEGE, vyssi odborna skola a jazykova skola s pravem statni jazykove zkousky Ostrava'
 where erasmus_code = 'CZ OSTRAVA04' and name <> 'EUROPEAN COLLEGE, vyssi odborna skola a jazykova skola s pravem statni jazykove zkousky Ostrava';
update public.universities set name = 'Filmova akademie Miroslava Ondricka v Pisku'
 where erasmus_code = 'CZ PISEK01' and name <> 'Filmova akademie Miroslava Ondricka v Pisku';
update public.universities set name = 'Soukroma vyssi odborna skola filmova'
 where erasmus_code = 'CZ PISEK03' and name <> 'Soukroma vyssi odborna skola filmova';
update public.universities set name = 'EUROPEAN COLLEGE, vyssi odborna skola Plzen'
 where erasmus_code = 'CZ PLZEN02' and name <> 'EUROPEAN COLLEGE, vyssi odborna skola Plzen';
update public.universities set name = 'Ambis Univerzita'
 where erasmus_code = 'CZ PRAHA11' and name <> 'Ambis Univerzita';
update public.universities set name = 'Vysoka Skola Financni a Spravni'
 where erasmus_code = 'CZ PRAHA13' and name <> 'Vysoka Skola Financni a Spravni';
update public.universities set name = 'Anglo-americka Vysoka Skola'
 where erasmus_code = 'CZ PRAHA17' and name <> 'Anglo-americka Vysoka Skola';
update public.universities set name = 'Metropolitni Univerzita Praha'
 where erasmus_code = 'CZ PRAHA18' and name <> 'Metropolitni Univerzita Praha';
update public.universities set name = 'Vysoka skola zdravotnicka'
 where erasmus_code = 'CZ PRAHA23' and name <> 'Vysoka skola zdravotnicka';
update public.universities set name = 'Unicorn Vysoka skola'
 where erasmus_code = 'CZ PRAHA26' and name <> 'Unicorn Vysoka skola';
update public.universities set name = 'Prazska vysoka skola psychosocialnich studii'
 where erasmus_code = 'CZ PRAHA28' and name <> 'Prazska vysoka skola psychosocialnich studii';
update public.universities set name = 'CEVRO Univerzita'
 where erasmus_code = 'CZ PRAHA30' and name <> 'CEVRO Univerzita';
update public.universities set name = 'Vysoka skola podnikani a prava'
 where erasmus_code = 'CZ PRAHA39' and name <> 'Vysoka skola podnikani a prava';
update public.universities set name = 'University of New York in Prague'
 where erasmus_code = 'CZ PRAHA40' and name <> 'University of New York in Prague';
update public.universities set name = 'Vysoka skola kreativni komunikace'
 where erasmus_code = 'CZ PRAHA42' and name <> 'Vysoka skola kreativni komunikace';
update public.universities set name = 'EUROPEAN COLLEGE, vyssi odborna skola Praha'
 where erasmus_code = 'CZ PRAHA45' and name <> 'EUROPEAN COLLEGE, vyssi odborna skola Praha';
update public.universities set name = 'Vysoka skola logistiky'
 where erasmus_code = 'CZ PREROV01' and name <> 'Vysoka skola logistiky';
update public.universities set name = 'Vysoka skola ekonomie a managementu'
 where erasmus_code = 'CZ USTINAD02' and name <> 'Vysoka skola ekonomie a managementu';
update public.universities set name = 'Alanus Hochschule'
 where erasmus_code = 'D ALFTER01' and name <> 'Alanus Hochschule';
update public.universities set name = 'Iu Internationale Hochschule'
 where erasmus_code = 'D BAD HON01' and name <> 'Iu Internationale Hochschule';
update public.universities set name = 'Hertie School Gemmeinnutzige'
 where erasmus_code = 'D BERLIN25' and name <> 'Hertie School Gemmeinnutzige';
update public.universities set name = 'International Psychoanalytic University Berlin'
 where erasmus_code = 'D BERLIN32' and name <> 'International Psychoanalytic University Berlin';
update public.universities set name = 'Bard College Berlin, a Liberal Artsuniversity'
 where erasmus_code = 'D BERLIN33' and name <> 'Bard College Berlin, a Liberal Artsuniversity';
update public.universities set name = 'Europaische Sportacademie Land Brandenburg'
 where erasmus_code = 'D BERLIN36' and name <> 'Europaische Sportacademie Land Brandenburg';
update public.universities set name = 'Msb Medical School Berlin'
 where erasmus_code = 'D BERLIN38' and name <> 'Msb Medical School Berlin';
update public.universities set name = 'Victoria'
 where erasmus_code = 'D BERLIN40' and name <> 'Victoria';
update public.universities set name = 'Escp Europe Wirtschaftshochschule Berlin'
 where erasmus_code = 'D BERLIN43' and name <> 'Escp Europe Wirtschaftshochschule Berlin';
update public.universities set name = 'Esmt European School of Management and Technology'
 where erasmus_code = 'D BERLIN46' and name <> 'Esmt European School of Management and Technology';
update public.universities set name = 'CODE Education'
 where erasmus_code = 'D BERLIN48' and name <> 'CODE Education';
update public.universities set name = 'Fachhochschule des Mittelstandes (Fhm)'
 where erasmus_code = 'D BIELEFE05' and name <> 'Fachhochschule des Mittelstandes (Fhm)';
update public.universities set name = 'Dmt-gesellschaft Fur Lehre Und Bildung'
 where erasmus_code = 'D BOCHUM05' and name <> 'Dmt-gesellschaft Fur Lehre Und Bildung';
update public.universities set name = 'Medizinische Hochschule Brandenburg Campus'
 where erasmus_code = 'D BRANDEN02' and name <> 'Medizinische Hochschule Brandenburg Campus';
update public.universities set name = 'Constructor University Bremen'
 where erasmus_code = 'D BREMEN09' and name <> 'Constructor University Bremen';
update public.universities set name = 'Europäische Fachhochschule Rhein/Erft'
 where erasmus_code = 'D BRUHL01' and name <> 'Europäische Fachhochschule Rhein/Erft';
update public.universities set name = 'Hochschule 21'
 where erasmus_code = 'D BUXTEHU02' and name <> 'Hochschule 21';
update public.universities set name = 'ISM International School of Management'
 where erasmus_code = 'D DORTMUN04' and name <> 'ISM International School of Management';
update public.universities set name = 'Fachhochschule Dresden Private Fachhochschule'
 where erasmus_code = 'D DRESDEN10' and name <> 'Fachhochschule Dresden Private Fachhochschule';
update public.universities set name = 'Ist-hochschule Fur Management'
 where erasmus_code = 'D DUSSELD08' and name <> 'Ist-hochschule Fur Management';
update public.universities set name = 'Hochschule für angewandtes Management'
 where erasmus_code = 'D ERDING01' and name <> 'Hochschule für angewandtes Management';
update public.universities set name = 'FOM Hochschule für Oekonomie & Management'
 where erasmus_code = 'D ESSEN03' and name <> 'FOM Hochschule für Oekonomie & Management';
update public.universities set name = 'HBK Essen'
 where erasmus_code = 'D ESSEN05' and name <> 'HBK Essen';
update public.universities set name = 'Frankfurt School of Finance & Management'
 where erasmus_code = 'D FRANKFU07' and name <> 'Frankfurt School of Finance & Management';
update public.universities set name = 'accadis Bildung'
 where erasmus_code = 'D FRANKFU10' and name <> 'accadis Bildung';
update public.universities set name = 'Katholische Hochschule Freiburg'
 where erasmus_code = 'D FREIBUR04' and name <> 'Katholische Hochschule Freiburg';
update public.universities set name = 'Zeppelin Universitat'
 where erasmus_code = 'D FRIEDRI01' and name <> 'Zeppelin Universitat';
update public.universities set name = 'SRH Hochschule für Gesundheit'
 where erasmus_code = 'D GERA01' and name <> 'SRH Hochschule für Gesundheit';
update public.universities set name = 'Gesellschaft Fur Praxisbezogene Forschung Und Wissenschaftliche Lehre'
 where erasmus_code = 'D GOTTING02' and name <> 'Gesellschaft Fur Praxisbezogene Forschung Und Wissenschaftliche Lehre';
update public.universities set name = 'Bucerius Law School - Hochschule für Rechtswissenschaft'
 where erasmus_code = 'D HAMBURG10' and name <> 'Bucerius Law School - Hochschule für Rechtswissenschaft';
update public.universities set name = 'Hamburg Media School'
 where erasmus_code = 'D HAMBURG11' and name <> 'Hamburg Media School';
update public.universities set name = 'Hamburg School of Business Administration'
 where erasmus_code = 'D HAMBURG13' and name <> 'Hamburg School of Business Administration';
update public.universities set name = 'Msh Medical School Hamburg'
 where erasmus_code = 'D HAMBURG18' and name <> 'Msh Medical School Hamburg';
update public.universities set name = 'Kuhne Logistics University'
 where erasmus_code = 'D HAMBURG19' and name <> 'Kuhne Logistics University';
update public.universities set name = 'Nbs Northern Business School'
 where erasmus_code = 'D HAMBURG21' and name <> 'Nbs Northern Business School';
update public.universities set name = 'Bildungszentrum F.Informationsverarbeitende Berufe'
 where erasmus_code = 'D HANNOVE09' and name <> 'Bildungszentrum F.Informationsverarbeitende Berufe';
update public.universities set name = 'Srh Hochschulen'
 where erasmus_code = 'D HEIDELB05' and name <> 'Srh Hochschulen';
update public.universities set name = 'Hochschulen Fresenius Gemeinnutzige Tragergesellschaft'
 where erasmus_code = 'D IDSTEIN01' and name <> 'Hochschulen Fresenius Gemeinnutzige Tragergesellschaft';
update public.universities set name = 'University of Europe For Applied Sciences'
 where erasmus_code = 'D ISERLOH02' and name <> 'University of Europe For Applied Sciences';
update public.universities set name = 'Karlshochschule'
 where erasmus_code = 'D KARLSRU08' and name <> 'Karlshochschule';
update public.universities set name = 'Hochschule für Gesellschaftsgestaltung (HfGG), rechtlich unselbständige Stiftung in der Cusanus Treuhand'
 where erasmus_code = 'D KOBLENZ04' and name <> 'Hochschule für Gesellschaftsgestaltung (HfGG), rechtlich unselbständige Stiftung in der Cusanus Treuhand';
update public.universities set name = 'RFH-Koeln'
 where erasmus_code = 'D KOLN07' and name <> 'RFH-Koeln';
update public.universities set name = 'CBS Cologne Business School'
 where erasmus_code = 'D KOLN12' and name <> 'CBS Cologne Business School';
update public.universities set name = 'HSD Hochschule Döpfer'
 where erasmus_code = 'D KOLN14' and name <> 'HSD Hochschule Döpfer';
update public.universities set name = 'Hhl'
 where erasmus_code = 'D LEIPZIG09' and name <> 'Hhl';
update public.universities set name = 'Popakademie Baden-Württemberg'
 where erasmus_code = 'D MANNHEI09' and name <> 'Popakademie Baden-Württemberg';
update public.universities set name = 'Hochschule der Wirtschaft Fur Management'
 where erasmus_code = 'D MANNHEI10' and name <> 'Hochschule der Wirtschaft Fur Management';
update public.universities set name = 'Sprachen- Und Dolmetscher-institutmunchen'
 where erasmus_code = 'D MUNCHEN11' and name <> 'Sprachen- Und Dolmetscher-institutmunchen';
update public.universities set name = 'Munich Business School'
 where erasmus_code = 'D MUNCHEN12' and name <> 'Munich Business School';
update public.universities set name = 'Mediadesign Hochschule Fur Design Und Informatik'
 where erasmus_code = 'D MUNCHEN14' and name <> 'Mediadesign Hochschule Fur Design Und Informatik';
update public.universities set name = 'Macromedia'
 where erasmus_code = 'D MUNCHEN15' and name <> 'Macromedia';
update public.universities set name = 'Hochschule der Bayerischen Wirtschaft'
 where erasmus_code = 'D MUNCHEN18' and name <> 'Hochschule der Bayerischen Wirtschaft';
update public.universities set name = 'Fachhochschule der Wirtschaft Nordrhein-Westfalen'
 where erasmus_code = 'D PADERBO04' and name <> 'Fachhochschule der Wirtschaft Nordrhein-Westfalen';
update public.universities set name = 'XU Exponential University of Applied Sciences'
 where erasmus_code = 'D POTSDAM06' and name <> 'XU Exponential University of Applied Sciences';
update public.universities set name = 'Merz Akademie'
 where erasmus_code = 'D STUTTGA09' and name <> 'Merz Akademie';
update public.universities set name = 'Verein zur Forderung der Freien Hochschule Stuttgart'
 where erasmus_code = 'D STUTTGA13' and name <> 'Verein zur Forderung der Freien Hochschule Stuttgart';
update public.universities set name = 'Private Hochschule für Wirtschaft und Technik'
 where erasmus_code = 'D VECHTA03' and name <> 'Private Hochschule für Wirtschaft und Technik';
update public.universities set name = 'Fachhochschule Wedel'
 where erasmus_code = 'D WEDEL H01' and name <> 'Fachhochschule Wedel';
update public.universities set name = 'Private Universitaet Witten/Herdecke'
 where erasmus_code = 'D WITTEN02' and name <> 'Private Universitaet Witten/Herdecke';
update public.universities set name = 'Theologische Hochschule Elstal im Bund Evangelisch-Freikirchlicher Gemeinden in Deutschland K.D.ö.R.'
 where erasmus_code = 'D WUSTERM01' and name <> 'Theologische Hochschule Elstal im Bund Evangelisch-Freikirchlicher Gemeinden in Deutschland K.D.ö.R.';
update public.universities set name = 'I.E.S. Antonio José Cavanilles'
 where erasmus_code = 'E ALICANT15' and name <> 'I.E.S. Antonio José Cavanilles';
update public.universities set name = 'I.E.S. Antonio Serna Serna'
 where erasmus_code = 'E ALICANT35' and name <> 'I.E.S. Antonio Serna Serna';
update public.universities set name = 'Instituto Mediterráneo de Estudios de Protocolo y Relaciones Institucionales'
 where erasmus_code = 'E ALICANT57' and name <> 'Instituto Mediterráneo de Estudios de Protocolo y Relaciones Institucionales';
update public.universities set name = 'I.E.S. Alhamilla'
 where erasmus_code = 'E ALMERIA08' and name <> 'I.E.S. Alhamilla';
update public.universities set name = 'I.E.S. Turaniana'
 where erasmus_code = 'E ALMERIA11' and name <> 'I.E.S. Turaniana';
update public.universities set name = 'Escuela Agraria'
 where erasmus_code = 'E ALMERIA27' and name <> 'Escuela Agraria';
update public.universities set name = 'I.E.S Rodriguez Moñino'
 where erasmus_code = 'E BADAJOZ34' and name <> 'I.E.S Rodriguez Moñino';
update public.universities set name = 'Col·legi Badalonès'
 where erasmus_code = 'E BARCELO116' and name <> 'Col·legi Badalonès';
update public.universities set name = 'Nova Eòlia'
 where erasmus_code = 'E BARCELO130' and name <> 'Nova Eòlia';
update public.universities set name = 'Centre d''Estudis Politècnics'
 where erasmus_code = 'E BARCELO141' and name <> 'Centre d''Estudis Politècnics';
update public.universities set name = 'Institució Escolar Túrbula'
 where erasmus_code = 'E BARCELO191' and name <> 'Institució Escolar Túrbula';
update public.universities set name = 'Instituto Técnico de Enseñanza y Servicios'
 where erasmus_code = 'E BARCELO197' and name <> 'Instituto Técnico de Enseñanza y Servicios';
update public.universities set name = 'Rosmenta'
 where erasmus_code = 'E BARCELO200' and name <> 'Rosmenta';
update public.universities set name = 'Centro de Estudios Dolmen'
 where erasmus_code = 'E BARCELO207' and name <> 'Centro de Estudios Dolmen';
update public.universities set name = 'Euroaula'
 where erasmus_code = 'E BARCELO211' and name <> 'Euroaula';
update public.universities set name = 'Escola Ginebró'
 where erasmus_code = 'E BARCELO232' and name <> 'Escola Ginebró';
update public.universities set name = 'Colegio Sant Marc de Sarrià'
 where erasmus_code = 'E BARCELO250' and name <> 'Colegio Sant Marc de Sarrià';
update public.universities set name = 'Jam Session Enseñanza musical'
 where erasmus_code = 'E BARCELO259' and name <> 'Jam Session Enseñanza musical';
update public.universities set name = 'Escoles Familiars Rurals d''Osona'
 where erasmus_code = 'E BARCELO265' and name <> 'Escoles Familiars Rurals d''Osona';
update public.universities set name = 'Lci Barcelona Escuela Superior'
 where erasmus_code = 'E BARCELO33' and name <> 'Lci Barcelona Escuela Superior';
update public.universities set name = 'Escola Universitaria Mediterrani'
 where erasmus_code = 'E BARCELO87' and name <> 'Escola Universitaria Mediterrani';
update public.universities set name = 'C.I.F.P. Emilio Campuzano L.H.I.I.'
 where erasmus_code = 'E BILBAO10' and name <> 'C.I.F.P. Emilio Campuzano L.H.I.I.';
update public.universities set name = 'Zabalburu Ikastetxea'
 where erasmus_code = 'E BILBAO13' and name <> 'Zabalburu Ikastetxea';
update public.universities set name = 'Centro San Luis'
 where erasmus_code = 'E BILBAO20' and name <> 'Centro San Luis';
update public.universities set name = 'Politeknika Ikastegia Txorierri'
 where erasmus_code = 'E BILBAO28' and name <> 'Politeknika Ikastegia Txorierri';
update public.universities set name = 'Almi Bilbao'
 where erasmus_code = 'E BILBAO43' and name <> 'Almi Bilbao';
update public.universities set name = 'Centro de Estudios Mikeldi'
 where erasmus_code = 'E BILBAO45' and name <> 'Centro de Estudios Mikeldi';
update public.universities set name = 'Asesoramiento y Formación Ikasauto'
 where erasmus_code = 'E BILBAO55' and name <> 'Asesoramiento y Formación Ikasauto';
update public.universities set name = 'Ibar Ezkerra Ikastola'
 where erasmus_code = 'E BILBAO61' and name <> 'Ibar Ezkerra Ikastola';
update public.universities set name = 'Ceinmark-Bilsan Informática'
 where erasmus_code = 'E BILBAO67' and name <> 'Ceinmark-Bilsan Informática';
update public.universities set name = 'Armengol Irudi'
 where erasmus_code = 'E BILBAO76' and name <> 'Armengol Irudi';
update public.universities set name = 'Educación y Tecnología de Extremadura'
 where erasmus_code = 'E CACERES14' and name <> 'Educación y Tecnología de Extremadura';
update public.universities set name = 'I.E.S. Santa Isabel de Hungria'
 where erasmus_code = 'E CADIZ21' and name <> 'I.E.S. Santa Isabel de Hungria';
update public.universities set name = 'C.E. Manuel Lora Tamayo'
 where erasmus_code = 'E CADIZ29' and name <> 'C.E. Manuel Lora Tamayo';
update public.universities set name = 'C.P.I.F.P. Marítimo Zaporito'
 where erasmus_code = 'E CADIZ33' and name <> 'C.P.I.F.P. Marítimo Zaporito';
update public.universities set name = 'Centro de Formación Profesional Sigler'
 where erasmus_code = 'E CADIZ40' and name <> 'Centro de Formación Profesional Sigler';
update public.universities set name = 'Ces Juan Pablo ll'
 where erasmus_code = 'E CADIZ62' and name <> 'Ces Juan Pablo ll';
update public.universities set name = 'Centro de Formacion y Orientacion Profesional Puente Europa'
 where erasmus_code = 'E CADIZ64' and name <> 'Centro de Formacion y Orientacion Profesional Puente Europa';
update public.universities set name = 'Colegio San Cristobal'
 where erasmus_code = 'E CASTELL31' and name <> 'Colegio San Cristobal';
update public.universities set name = 'I.E.S. Francisco Garcia Pavon'
 where erasmus_code = 'E CIUDA R19' and name <> 'I.E.S. Francisco Garcia Pavon';
update public.universities set name = 'I.E.S. Pedro Mercedes'
 where erasmus_code = 'E CUENCA02' and name <> 'I.E.S. Pedro Mercedes';
update public.universities set name = 'I.E.S. Fray Luis de Granada'
 where erasmus_code = 'E GRANADA24' and name <> 'I.E.S. Fray Luis de Granada';
update public.universities set name = 'Escuela Diseño Granada'
 where erasmus_code = 'E GRANADA35' and name <> 'Escuela Diseño Granada';
update public.universities set name = 'Atlantida Formacion'
 where erasmus_code = 'E GRANADA44' and name <> 'Atlantida Formacion';
update public.universities set name = 'Escuela Superior de Arte y Diseño Esada Ii'
 where erasmus_code = 'E GRANADA53' and name <> 'Escuela Superior de Arte y Diseño Esada Ii';
update public.universities set name = 'I.E.S. Brianda de Mendoza'
 where erasmus_code = 'E GUADALA09' and name <> 'I.E.S. Brianda de Mendoza';
update public.universities set name = 'Centro de Estudios Superiores Universitarios de Galicia'
 where erasmus_code = 'E LA CORU40' and name <> 'Centro de Estudios Superiores Universitarios de Galicia';
update public.universities set name = 'Master del Conocimiento'
 where erasmus_code = 'E LAS PAL43' and name <> 'Master del Conocimiento';
update public.universities set name = 'Mercurio Bierzo'
 where erasmus_code = 'E LEON18' and name <> 'Mercurio Bierzo';
update public.universities set name = 'Centro Integral de Fp Ilerna'
 where erasmus_code = 'E LLEIDA11' and name <> 'Centro Integral de Fp Ilerna';
update public.universities set name = 'I.E.S. Virgen de la Paz'
 where erasmus_code = 'E MADRID128' and name <> 'I.E.S. Virgen de la Paz';
update public.universities set name = 'I.E.S. Humanejos'
 where erasmus_code = 'E MADRID142' and name <> 'I.E.S. Humanejos';
update public.universities set name = 'I.E.S. Pintor Antonio López'
 where erasmus_code = 'E MADRID155' and name <> 'I.E.S. Pintor Antonio López';
update public.universities set name = 'I.E.S Enrique Tierno Galván'
 where erasmus_code = 'E MADRID168' and name <> 'I.E.S Enrique Tierno Galván';
update public.universities set name = 'Saint Charles College'
 where erasmus_code = 'E MADRID172' and name <> 'Saint Charles College';
update public.universities set name = 'Fuenllana Centro Cultural Pedralta'
 where erasmus_code = 'E MADRID183' and name <> 'Fuenllana Centro Cultural Pedralta';
update public.universities set name = 'U-tad Centro Digital'
 where erasmus_code = 'E MADRID189' and name <> 'U-tad Centro Digital';
update public.universities set name = 'I.E.S Isaac Peral'
 where erasmus_code = 'E MADRID193' and name <> 'I.E.S Isaac Peral';
update public.universities set name = 'Emprende y Gestiona 2015'
 where erasmus_code = 'E MADRID201' and name <> 'Emprende y Gestiona 2015';
update public.universities set name = 'Udit Estudios Superiores Internacionales'
 where erasmus_code = 'E MADRID205' and name <> 'Udit Estudios Superiores Internacionales';
update public.universities set name = 'Centro Español de Tecnologia Aplicada'
 where erasmus_code = 'E MADRID210' and name <> 'Centro Español de Tecnologia Aplicada';
update public.universities set name = 'Imf International Business School'
 where erasmus_code = 'E MADRID214' and name <> 'Imf International Business School';
update public.universities set name = 'Taller Cefora'
 where erasmus_code = 'E MADRID224' and name <> 'Taller Cefora';
update public.universities set name = 'Formajobs'
 where erasmus_code = 'E MADRID227' and name <> 'Formajobs';
update public.universities set name = 'Centro de Estudios Linkia FP Madrid'
 where erasmus_code = 'E MADRID233' and name <> 'Centro de Estudios Linkia FP Madrid';
update public.universities set name = 'Unie Universidad'
 where erasmus_code = 'E MADRID238' and name <> 'Unie Universidad';
update public.universities set name = 'Institutos Nebrija'
 where erasmus_code = 'E MADRID247' and name <> 'Institutos Nebrija';
update public.universities set name = 'Katarina Gurska'
 where erasmus_code = 'E MADRID252' and name <> 'Katarina Gurska';
update public.universities set name = 'Cepif Professional Training'
 where erasmus_code = 'E MADRID254' and name <> 'Cepif Professional Training';
update public.universities set name = 'Investigación y desarrollo pedagógico'
 where erasmus_code = 'E MADRID261' and name <> 'Investigación y desarrollo pedagógico';
update public.universities set name = 'Udit Escuela de Formación Profesional'
 where erasmus_code = 'E MADRID262' and name <> 'Udit Escuela de Formación Profesional';
update public.universities set name = 'Proeduca Formación Profesional Global'
 where erasmus_code = 'E MADRID263' and name <> 'Proeduca Formación Profesional Global';
update public.universities set name = 'Espacios Educativos'
 where erasmus_code = 'E MADRID265' and name <> 'Espacios Educativos';
update public.universities set name = 'I.E.S. Centro de Capacitación Agraria'
 where erasmus_code = 'E MADRID82' and name <> 'I.E.S. Centro de Capacitación Agraria';
update public.universities set name = 'I.E.S. Luis Vives'
 where erasmus_code = 'E MADRID86' and name <> 'I.E.S. Luis Vives';
update public.universities set name = 'I.E.S. Juan de la Cierva'
 where erasmus_code = 'E MADRID92' and name <> 'I.E.S. Juan de la Cierva';
update public.universities set name = 'I.E.S. Litoral'
 where erasmus_code = 'E MALAGA55' and name <> 'I.E.S. Litoral';
update public.universities set name = 'Colegio el Pinar'
 where erasmus_code = 'E MALAGA63' and name <> 'Colegio el Pinar';
update public.universities set name = 'EADE-Diseños'
 where erasmus_code = 'E MALAGA66' and name <> 'EADE-Diseños';
update public.universities set name = 'Iniciativa Educativa Uea'
 where erasmus_code = 'E MALAGA67' and name <> 'Iniciativa Educativa Uea';
update public.universities set name = 'Mondragon Goi Eskola Politeknikoa Jose Maria Arizmendiarrieta'
 where erasmus_code = 'E MONDRAG02' and name <> 'Mondragon Goi Eskola Politeknikoa Jose Maria Arizmendiarrieta';
update public.universities set name = 'Huhezi'
 where erasmus_code = 'E MONDRAG03' and name <> 'Huhezi';
update public.universities set name = 'Ces Vegamedia'
 where erasmus_code = 'E MURCIA51' and name <> 'Ces Vegamedia';
update public.universities set name = 'ISEN Formación'
 where erasmus_code = 'E MURCIA85' and name <> 'ISEN Formación';
update public.universities set name = 'Escuela de Turismo de Baleares'
 where erasmus_code = 'E PALMA47' and name <> 'Escuela de Turismo de Baleares';
update public.universities set name = 'Es Liceu'
 where erasmus_code = 'E PALMA49' and name <> 'Es Liceu';
update public.universities set name = 'C.I. Agroforestal Ii'
 where erasmus_code = 'E PAMPLON13' and name <> 'C.I. Agroforestal Ii';
update public.universities set name = 'Creanavarra Centro superior de Diseño'
 where erasmus_code = 'E PAMPLON27' and name <> 'Creanavarra Centro superior de Diseño';
update public.universities set name = 'I.E.S. Fermin Bouza Brey'
 where erasmus_code = 'E PONTEVE10' and name <> 'I.E.S. Fermin Bouza Brey';
update public.universities set name = 'Cebanc'
 where erasmus_code = 'E SAN SEB02' and name <> 'Cebanc';
update public.universities set name = 'Tolosako Inmakulada Lanbide Ikastola'
 where erasmus_code = 'E SAN SEB07' and name <> 'Tolosako Inmakulada Lanbide Ikastola';
update public.universities set name = 'C.I.F.P. Armeria Eskola L.H.I.I.'
 where erasmus_code = 'E SAN SEB13' and name <> 'C.I.F.P. Armeria Eskola L.H.I.I.';
update public.universities set name = 'Escuela de Cine y Video'
 where erasmus_code = 'E SAN SEB15' and name <> 'Escuela de Cine y Video';
update public.universities set name = 'Mu Enpresagintza'
 where erasmus_code = 'E SAN SEB21' and name <> 'Mu Enpresagintza';
update public.universities set name = 'Cesa Centro de Estudios Sanitarios'
 where erasmus_code = 'E SAN SEB49' and name <> 'Cesa Centro de Estudios Sanitarios';
update public.universities set name = 'I.E.S. Las Llamas'
 where erasmus_code = 'E SANTAND07' and name <> 'I.E.S. Las Llamas';
update public.universities set name = 'I.E.S. la Albericia'
 where erasmus_code = 'E SANTAND24' and name <> 'I.E.S. la Albericia';
update public.universities set name = 'Cesinec'
 where erasmus_code = 'E SANTAND35' and name <> 'Cesinec';
update public.universities set name = 'Academia Crespo'
 where erasmus_code = 'E SANTAND36' and name <> 'Academia Crespo';
update public.universities set name = 'I.E.S. Francisco Giner de Los Ríos'
 where erasmus_code = 'E SEGOVIA07' and name <> 'I.E.S. Francisco Giner de Los Ríos';
update public.universities set name = 'Ilerna on Line'
 where erasmus_code = 'E SEVILLA102' and name <> 'Ilerna on Line';
update public.universities set name = 'Ribamar'
 where erasmus_code = 'E SEVILLA56' and name <> 'Ribamar';
update public.universities set name = 'S.A. Fomento Para Las Enseñanzas del Sur'
 where erasmus_code = 'E SEVILLA69' and name <> 'S.A. Fomento Para Las Enseñanzas del Sur';
update public.universities set name = 'I.E.S Luis Velez de Guevara'
 where erasmus_code = 'E SEVILLA86' and name <> 'I.E.S Luis Velez de Guevara';
update public.universities set name = 'Cepa'
 where erasmus_code = 'E SEVILLA94' and name <> 'Cepa';
update public.universities set name = 'I.E.S. la Laboral de la Laguna'
 where erasmus_code = 'E TENERIF10' and name <> 'I.E.S. la Laboral de la Laguna';
update public.universities set name = 'I.E.S. San Matias'
 where erasmus_code = 'E TENERIF30' and name <> 'I.E.S. San Matias';
update public.universities set name = 'I.E.S. la Orotava - Manuel González Pérez'
 where erasmus_code = 'E TENERIF35' and name <> 'I.E.S. la Orotava - Manuel González Pérez';
update public.universities set name = 'Escuela de Actores de Canarias'
 where erasmus_code = 'E TENERIF47' and name <> 'Escuela de Actores de Canarias';
update public.universities set name = 'Centro de Formación Formaj'
 where erasmus_code = 'E TOLEDO19' and name <> 'Centro de Formación Formaj';
update public.universities set name = 'Ces Juan Pablo Ii'
 where erasmus_code = 'E TOLEDO23' and name <> 'Ces Juan Pablo Ii';
update public.universities set name = 'Sociedad de Gestión Cámara Valencia'
 where erasmus_code = 'E VALENCI124' and name <> 'Sociedad de Gestión Cámara Valencia';
update public.universities set name = 'I.E.S. Joan Fuster (Sueca)'
 where erasmus_code = 'E VALENCI127' and name <> 'I.E.S. Joan Fuster (Sueca)';
update public.universities set name = 'Verge de Cortes'
 where erasmus_code = 'E VALENCI136' and name <> 'Verge de Cortes';
update public.universities set name = 'Tevian'
 where erasmus_code = 'E VALENCI61' and name <> 'Tevian';
update public.universities set name = 'Colegio Mas Camarena'
 where erasmus_code = 'E VALENCI89' and name <> 'Colegio Mas Camarena';
update public.universities set name = 'Universidad Europea Miguel de Cervantes'
 where erasmus_code = 'E VALLADO03' and name <> 'Universidad Europea Miguel de Cervantes';
update public.universities set name = 'Formación y Tecnologia Educativa En Castilla y León'
 where erasmus_code = 'E VALLADO28' and name <> 'Formación y Tecnologia Educativa En Castilla y León';
update public.universities set name = 'Escuela Superior de Diseño de Valaldolid'
 where erasmus_code = 'E VALLADO32' and name <> 'Escuela Superior de Diseño de Valaldolid';
update public.universities set name = 'I.E.S. Politécnico de Vigo'
 where erasmus_code = 'E VIGO06' and name <> 'I.E.S. Politécnico de Vigo';
update public.universities set name = 'Fomento de Centros de Enseñanza, S.A. - Colegio Montecastelo'
 where erasmus_code = 'E VIGO09' and name <> 'Fomento de Centros de Enseñanza, S.A. - Colegio Montecastelo';
update public.universities set name = 'Colegio Vivas'
 where erasmus_code = 'E VIGO21' and name <> 'Colegio Vivas';
update public.universities set name = 'C.I.F.P. Ciudad Jardin'
 where erasmus_code = 'E VITORIA07' and name <> 'C.I.F.P. Ciudad Jardin';
update public.universities set name = 'Unversidad Euneiz'
 where erasmus_code = 'E VITORIA26' and name <> 'Unversidad Euneiz';
update public.universities set name = 'Centro Montessori Aragón'
 where erasmus_code = 'E ZARAGOZ08' and name <> 'Centro Montessori Aragón';
update public.universities set name = 'CEFOR Izquierdo'
 where erasmus_code = 'E ZARAGOZ15' and name <> 'CEFOR Izquierdo';
update public.universities set name = 'Academia Marco'
 where erasmus_code = 'E ZARAGOZ46' and name <> 'Academia Marco';
update public.universities set name = 'Eesti Ettevõtluskõrgkool Mainor'
 where erasmus_code = 'EE TALLINN15' and name <> 'Eesti Ettevõtluskõrgkool Mainor';
update public.universities set name = 'E.S. le Mirail'
 where erasmus_code = 'F BORDEAU67' and name <> 'E.S. le Mirail';
update public.universities set name = 'Lycee General Technologique J.M.Carriat'
 where erasmus_code = 'F BOURG B11' and name <> 'Lycee General Technologique J.M.Carriat';
update public.universities set name = 'Lycee Professionnel la Providence'
 where erasmus_code = 'F CHOLET03' and name <> 'Lycee Professionnel la Providence';
update public.universities set name = 'Lycee General & Technologique V.Schoelcher'
 where erasmus_code = 'F FORT FR14' and name <> 'Lycee General & Technologique V.Schoelcher';
update public.universities set name = 'association andré coindre'
 where erasmus_code = 'F LANGOGN01' and name <> 'association andré coindre';
update public.universities set name = 'Association Regionale du Travail Social Hauts de France (A.R.T.S)'
 where erasmus_code = 'F LOOS02' and name <> 'Association Regionale du Travail Social Hauts de France (A.R.T.S)';
update public.universities set name = 'Centre D''etudes Europeen Rhone Alpes- C.E.E. Rhone Alpes'
 where erasmus_code = 'F LYON71' and name <> 'Centre D''etudes Europeen Rhone Alpes- C.E.E. Rhone Alpes';
update public.universities set name = 'Lycee General Et Techno. E.Delacroix'
 where erasmus_code = 'F MAISONS02' and name <> 'Lycee General Et Techno. E.Delacroix';
update public.universities set name = 'Ecole D''enseignement Superieur Prive I.C.N.'
 where erasmus_code = 'F NANCY37' and name <> 'Ecole D''enseignement Superieur Prive I.C.N.';
update public.universities set name = 'E.A.C Centre D''etudes Superieures En Economie Art Et Communication'
 where erasmus_code = 'F PARIS343' and name <> 'E.A.C Centre D''etudes Superieures En Economie Art Et Communication';
update public.universities set name = 'Association O.R.T.'
 where erasmus_code = 'F PARIS518' and name <> 'Association O.R.T.';
update public.universities set name = 'O.G.E.C. la Joliverie'
 where erasmus_code = 'F STE SEB01' and name <> 'O.G.E.C. la Joliverie';
update public.universities set name = 'E.P.A.G. Axe Sud'
 where erasmus_code = 'F TOULOUS117' and name <> 'E.P.A.G. Axe Sud';
update public.universities set name = 'Poliarte Politecnico delle arti'
 where erasmus_code = 'I ANCONA02' and name <> 'Poliarte Politecnico delle arti';
update public.universities set name = 'I.T.S. Antonio Cuccovillo Sistema Meccanico-meccatronico'
 where erasmus_code = 'I BARI07' and name <> 'I.T.S. Antonio Cuccovillo Sistema Meccanico-meccatronico';
update public.universities set name = 'Italicampus S.R.L. Società Benefit'
 where erasmus_code = 'I BARI09' and name <> 'Italicampus S.R.L. Società Benefit';
update public.universities set name = 'Iformed Istituto Per la Formazione e la Mediazione'
 where erasmus_code = 'I BOLOGNA06' and name <> 'Iformed Istituto Per la Formazione e la Mediazione';
update public.universities set name = 'Laba'
 where erasmus_code = 'I BRESCIA05' and name <> 'Laba';
update public.universities set name = 'Scuola Superiore Universitaria Per Mediatori Linguistici del Molise'
 where erasmus_code = 'I CAMPOBA05' and name <> 'Scuola Superiore Universitaria Per Mediatori Linguistici del Molise';
update public.universities set name = 'Conservatorio Statale di Musica A.Steffani'
 where erasmus_code = 'I CASTELF01' and name <> 'Conservatorio Statale di Musica A.Steffani';
update public.universities set name = 'I.L.E.M.'
 where erasmus_code = 'I COMO03' and name <> 'I.L.E.M.';
update public.universities set name = 'Conservatorio Statale di Musica G.B. Pergolesi - Fermo'
 where erasmus_code = 'I FERMO01' and name <> 'Conservatorio Statale di Musica G.B. Pergolesi - Fermo';
update public.universities set name = 'Fondazione Scuola di Musica di Fiesole'
 where erasmus_code = 'I FIRENZE07' and name <> 'Fondazione Scuola di Musica di Fiesole';
update public.universities set name = 'Flores'
 where erasmus_code = 'I FIRENZE08' and name <> 'Flores';
update public.universities set name = 'Fusp'
 where erasmus_code = 'I FORLI01' and name <> 'Fusp';
update public.universities set name = 'Conservatorio di Musica G.Verdi di Milano'
 where erasmus_code = 'I MILANO09' and name <> 'Conservatorio di Musica G.Verdi di Milano';
update public.universities set name = 'Nuova Accademia'
 where erasmus_code = 'I MILANO11' and name <> 'Nuova Accademia';
update public.universities set name = 'Mussida Music Publishing'
 where erasmus_code = 'I MILANO24' and name <> 'Mussida Music Publishing';
update public.universities set name = 'Sae Italia S.R.L. International Technology College'
 where erasmus_code = 'I MILANO30' and name <> 'Sae Italia S.R.L. International Technology College';
update public.universities set name = 'ADLM S.R.L. a socio unico'
 where erasmus_code = 'I MILANO31' and name <> 'ADLM S.R.L. a socio unico';
update public.universities set name = 'Universita Telematica Pegaso'
 where erasmus_code = 'I NAPOLI11' and name <> 'Universita Telematica Pegaso';
update public.universities set name = 'Scuola del Teatro Musicale'
 where erasmus_code = 'I NOVARA02' and name <> 'Scuola del Teatro Musicale';
update public.universities set name = 'Istituto Universitario di Studi Superiori ( I.U.S.S.) di Pavia'
 where erasmus_code = 'I PAVIA03' and name <> 'Istituto Universitario di Studi Superiori ( I.U.S.S.) di Pavia';
update public.universities set name = 'Mediazione Linguistica Perugia'
 where erasmus_code = 'I PERUGIA05' and name <> 'Mediazione Linguistica Perugia';
update public.universities set name = 'Istituto Italiano di Design'
 where erasmus_code = 'I PERUGIA08' and name <> 'Istituto Italiano di Design';
update public.universities set name = 'Istituto Generale Istruzione Superiore'
 where erasmus_code = 'I QUARTUS01' and name <> 'Istituto Generale Istruzione Superiore';
update public.universities set name = 'Saint Louis Music Center'
 where erasmus_code = 'I ROMA30' and name <> 'Saint Louis Music Center';
update public.universities set name = 'International Campus'
 where erasmus_code = 'I ROMA32' and name <> 'International Campus';
update public.universities set name = 'Universita Telematica San Raffaele Roma'
 where erasmus_code = 'I ROMA35' and name <> 'Universita Telematica San Raffaele Roma';
update public.universities set name = 'Istituto di Cultura Pantheon'
 where erasmus_code = 'I ROMA38' and name <> 'Istituto di Cultura Pantheon';
update public.universities set name = 'DuofinArt'
 where erasmus_code = 'I ROMA39' and name <> 'DuofinArt';
update public.universities set name = 'Orizzonte Docenti'
 where erasmus_code = 'I ROMA44' and name <> 'Orizzonte Docenti';
update public.universities set name = 'Fondazione Accademia'
 where erasmus_code = 'I ROMA47' and name <> 'Fondazione Accademia';
update public.universities set name = 'Rosario Gagliardi'
 where erasmus_code = 'I SIRACUS06' and name <> 'Rosario Gagliardi';
update public.universities set name = 'I.T.S. Ge. In. Logistic'
 where erasmus_code = 'I TARANTO01' and name <> 'I.T.S. Ge. In. Logistic';
update public.universities set name = 'Holden'
 where erasmus_code = 'I TORINO17' and name <> 'Holden';
update public.universities set name = 'Accademia Tiepolo'
 where erasmus_code = 'I UDINE05' and name <> 'Accademia Tiepolo';
update public.universities set name = 'I.L.S.I.T.'
 where erasmus_code = 'I VARESE03' and name <> 'I.L.S.I.T.';
update public.universities set name = 'Its Marco Polo'
 where erasmus_code = 'I VENEZIA05' and name <> 'Its Marco Polo';
update public.universities set name = 'Unimedia'
 where erasmus_code = 'I VERONA05' and name <> 'Unimedia';
update public.universities set name = 'Conservatorio di Musica F.Torrefranca Vibo Valentia'
 where erasmus_code = 'I VIBO VA01' and name <> 'Conservatorio di Musica F.Torrefranca Vibo Valentia';
update public.universities set name = 'Bellerophon'
 where erasmus_code = 'IRLDUBLIN35' and name <> 'Bellerophon';
update public.universities set name = 'Hibernia College'
 where erasmus_code = 'IRLDUBLIN42' and name <> 'Hibernia College';
update public.universities set name = 'Computer Training Specialists'
 where erasmus_code = 'IRLDUBLIN43' and name <> 'Computer Training Specialists';
update public.universities set name = 'The American College, Dublin Company'
 where erasmus_code = 'IRLDUBLIN45' and name <> 'The American College, Dublin Company';
update public.universities set name = 'Galway Business School'
 where erasmus_code = 'IRLGALWAY03' and name <> 'Galway Business School';
update public.universities set name = 'Burren College of Art'
 where erasmus_code = 'IRLMUNST02' and name <> 'Burren College of Art';
update public.universities set name = 'St Angela''s College Sligo'
 where erasmus_code = 'IRLSLIGO02' and name <> 'St Angela''s College Sligo';
update public.universities set name = 'Lunex'
 where erasmus_code = 'LUXDIFFERD01' and name <> 'Lunex';
update public.universities set name = 'Luxembourg School of Business'
 where erasmus_code = 'LUXLUX VIL08' and name <> 'Luxembourg School of Business';
update public.universities set name = 'P.V.P.U.Euro Koledz Kumanovo'
 where erasmus_code = 'MK SKOPJE13' and name <> 'P.V.P.U.Euro Koledz Kumanovo';
update public.universities set name = 'St. Martin''s Education Services'
 where erasmus_code = 'MT MALTA06' and name <> 'St. Martin''s Education Services';
update public.universities set name = 'Aea'
 where erasmus_code = 'MT MALTA08' and name <> 'Aea';
update public.universities set name = 'Leadership Consultancy and Training Services'
 where erasmus_code = 'MT MALTA09' and name <> 'Leadership Consultancy and Training Services';
update public.universities set name = 'Pegaso International'
 where erasmus_code = 'MT MALTA10' and name <> 'Pegaso International';
update public.universities set name = 'Ascencia Malta'
 where erasmus_code = 'MT MALTA11' and name <> 'Ascencia Malta';
update public.universities set name = 'Knights College'
 where erasmus_code = 'MT MALTA12' and name <> 'Knights College';
update public.universities set name = 'Gbsb Global Business School'
 where erasmus_code = 'MT MALTA13' and name <> 'Gbsb Global Business School';
update public.universities set name = 'Learnkey'
 where erasmus_code = 'MT MALTA17' and name <> 'Learnkey';
update public.universities set name = 'Asomi College of Sciences'
 where erasmus_code = 'MT MALTA18' and name <> 'Asomi College of Sciences';
update public.universities set name = 'IDEA Academy'
 where erasmus_code = 'MT MALTA19' and name <> 'IDEA Academy';
update public.universities set name = 'European Global Varsity'
 where erasmus_code = 'MT MALTA20' and name <> 'European Global Varsity';
update public.universities set name = 'Nla Hogskolen'
 where erasmus_code = 'N BERGEN12' and name <> 'Nla Hogskolen';
update public.universities set name = 'Noroff University College'
 where erasmus_code = 'N KRISTIA05' and name <> 'Noroff University College';
update public.universities set name = 'Fjellhaug Internasjonale Høgskole'
 where erasmus_code = 'N OSLO65' and name <> 'Fjellhaug Internasjonale Høgskole';
update public.universities set name = 'Vid Vitenskapelige Hogskole'
 where erasmus_code = 'N OSLO67' and name <> 'Vid Vitenskapelige Hogskole';
update public.universities set name = 'Fagskolen Kristiania'
 where erasmus_code = 'N OSLO71' and name <> 'Fagskolen Kristiania';
update public.universities set name = 'Academica University of Applied Sciences'
 where erasmus_code = 'NL AMSTERD73' and name <> 'Academica University of Applied Sciences';
update public.universities set name = 'Unknown University of Applied Sciences'
 where erasmus_code = 'NL AMSTERD74' and name <> 'Unknown University of Applied Sciences';
update public.universities set name = 'Wittenborg University of Applied Sciences'
 where erasmus_code = 'NL APELDO07' and name <> 'Wittenborg University of Applied Sciences';
update public.universities set name = 'Netherlands Business Academy'
 where erasmus_code = 'NL BREDA11' and name <> 'Netherlands Business Academy';
update public.universities set name = 'Universiteit Nyenrode'
 where erasmus_code = 'NL BREUKEL01' and name <> 'Universiteit Nyenrode';
update public.universities set name = 'Tio Teach'
 where erasmus_code = 'NL UTRECHT35' and name <> 'Tio Teach';
update public.universities set name = 'Thim van der Laan'
 where erasmus_code = 'NL UTRECHT37' and name <> 'Thim van der Laan';
update public.universities set name = 'Instituto Piaget Coop Para o Desenvimento Humano Integral Ecologico'
 where erasmus_code = 'P LISBOA101' and name <> 'Instituto Piaget Coop Para o Desenvimento Humano Integral Ecologico';
update public.universities set name = 'Universitas Cooperativa de Ensino Superior e Investigacao Cientifica'
 where erasmus_code = 'P LISBOA104' and name <> 'Universitas Cooperativa de Ensino Superior e Investigacao Cientifica';
update public.universities set name = 'C.E.U - Cooperativa de Ensino Universitario'
 where erasmus_code = 'P LISBOA11' and name <> 'C.E.U - Cooperativa de Ensino Universitario';
update public.universities set name = 'Escola Superior Nautica Infante D.Henrique'
 where erasmus_code = 'P LISBOA111' and name <> 'Escola Superior Nautica Infante D.Henrique';
update public.universities set name = 'Ispa'
 where erasmus_code = 'P LISBOA17' and name <> 'Ispa';
update public.universities set name = 'Cofac Cooperativa de Formacao e Animacao Cultural'
 where erasmus_code = 'P LISBOA52' and name <> 'Cofac Cooperativa de Formacao e Animacao Cultural';
update public.universities set name = 'Maieutica Cooperativa de Ensino Superior'
 where erasmus_code = 'P MAIA01' and name <> 'Maieutica Cooperativa de Ensino Superior';
update public.universities set name = 'Universidade Portucalense Infante D Henrique-cooperativa de Ensino Superior'
 where erasmus_code = 'P PORTO07' and name <> 'Universidade Portucalense Infante D Henrique-cooperativa de Ensino Superior';
update public.universities set name = 'Academia Tehnica Militara Ferdinand i'
 where erasmus_code = 'RO BUCURES02' and name <> 'Academia Tehnica Militara Ferdinand i';
update public.universities set name = 'Hameen Ammattikorkeakoulu'
 where erasmus_code = 'SF HAMEENL09' and name <> 'Hameen Ammattikorkeakoulu';
update public.universities set name = 'Diakonia-ammattikorkeakoulu'
 where erasmus_code = 'SF HELSINK19' and name <> 'Diakonia-ammattikorkeakoulu';
update public.universities set name = 'Haaga-helia Ammattikorkeakoulu'
 where erasmus_code = 'SF HELSINK40' and name <> 'Haaga-helia Ammattikorkeakoulu';
update public.universities set name = 'Metropolia Ammattikorkeakoulu'
 where erasmus_code = 'SF HELSINK41' and name <> 'Metropolia Ammattikorkeakoulu';
update public.universities set name = 'Karelia Ammattikorkeakoulu'
 where erasmus_code = 'SF JOENSUU09' and name <> 'Karelia Ammattikorkeakoulu';
update public.universities set name = 'Jyvaskylan Ammattikorkeakoulu'
 where erasmus_code = 'SF JYVASKY11' and name <> 'Jyvaskylan Ammattikorkeakoulu';
update public.universities set name = 'Kajaanin Ammattikorkeakoulu'
 where erasmus_code = 'SF KAJAANI05' and name <> 'Kajaanin Ammattikorkeakoulu';
update public.universities set name = 'Centria-ammattikorkeakoulu'
 where erasmus_code = 'SF KOKKOLA05' and name <> 'Centria-ammattikorkeakoulu';
update public.universities set name = 'Savonia-ammattikorkeakoulu'
 where erasmus_code = 'SF KUOPIO08' and name <> 'Savonia-ammattikorkeakoulu';
update public.universities set name = 'Lab-ammattikorkeakoulu'
 where erasmus_code = 'SF LAHTI11' and name <> 'Lab-ammattikorkeakoulu';
update public.universities set name = 'Kaakkois-suomen Ammattikorkeakoulu'
 where erasmus_code = 'SF MIKKELI07' and name <> 'Kaakkois-suomen Ammattikorkeakoulu';
update public.universities set name = 'Oulun Ammattikorkeakoulu'
 where erasmus_code = 'SF OULU11' and name <> 'Oulun Ammattikorkeakoulu';
update public.universities set name = 'Satakunnan Ammattikorkeakoulu'
 where erasmus_code = 'SF PORI08' and name <> 'Satakunnan Ammattikorkeakoulu';
update public.universities set name = 'Lapin Ammattikorkeakoulu'
 where erasmus_code = 'SF ROVANIE11' and name <> 'Lapin Ammattikorkeakoulu';
update public.universities set name = 'Seinajoen Ammattikorkeakoulu'
 where erasmus_code = 'SF SEINAJO06' and name <> 'Seinajoen Ammattikorkeakoulu';
update public.universities set name = 'Tampereen Ammattikorkeakoulu'
 where erasmus_code = 'SF TAMPERE06' and name <> 'Tampereen Ammattikorkeakoulu';
update public.universities set name = 'Turun Ammattikorkeakoulu'
 where erasmus_code = 'SF TURKU05' and name <> 'Turun Ammattikorkeakoulu';
update public.universities set name = 'Laurea-ammattikorkeakoulu'
 where erasmus_code = 'SF VANTAA06' and name <> 'Laurea-ammattikorkeakoulu';
update public.universities set name = 'Izobrazevalni center Memory, izobrazevanje in svetovanje'
 where erasmus_code = 'SI DUTOVLJ02' and name <> 'Izobrazevalni center Memory, izobrazevanje in svetovanje';
update public.universities set name = 'B&B izobrazevanje in usposabljanje'
 where erasmus_code = 'SI KRANJ05' and name <> 'B&B izobrazevanje in usposabljanje';
update public.universities set name = 'Izobrazevalni Center Geoss'
 where erasmus_code = 'SI LJUBLJA25' and name <> 'Izobrazevalni Center Geoss';
update public.universities set name = 'ERUDIO izobrazevalni center, izobrazevanje D.O.O., ERUDIO Visja strokovna sola'
 where erasmus_code = 'SI LJUBLJA35' and name <> 'ERUDIO izobrazevalni center, izobrazevanje D.O.O., ERUDIO Visja strokovna sola';
update public.universities set name = 'Sofizo Izobrazevalni Center'
 where erasmus_code = 'SI LJUBLJA41' and name <> 'Sofizo Izobrazevalni Center';
update public.universities set name = 'Doba Epis'
 where erasmus_code = 'SI MARIBOR06' and name <> 'Doba Epis';
update public.universities set name = 'Academia, Izobrazevanje in Druge Storitve'
 where erasmus_code = 'SI MARIBOR07' and name <> 'Academia, Izobrazevanje in Druge Storitve';
update public.universities set name = 'Prah, izobrazevalni center, izobrazevanje in usposabljanje, D.O.O., Visja strokovna sola Rogaska Slatina'
 where erasmus_code = 'SI ROGASKA02' and name <> 'Prah, izobrazevalni center, izobrazevanje in usposabljanje, D.O.O., Visja strokovna sola Rogaska Slatina';
update public.universities set name = 'Dubnicky Technologicky Institut V Dubnicki Nad Vahom'
 where erasmus_code = 'SK DUBNICA01' and name <> 'Dubnicky Technologicky Institut V Dubnicki Nad Vahom';
update public.universities set name = 'Vysoka Skola Bezpecnostneho Manazerstva'
 where erasmus_code = 'SK KOSICE05' and name <> 'Vysoka Skola Bezpecnostneho Manazerstva';
update public.universities set name = 'T.C Beykent Universitesi'
 where erasmus_code = 'TR ISTANBU09' and name <> 'T.C Beykent Universitesi';
update public.universities set name = 'Kolegji Universum O.P'
 where erasmus_code = 'XK FERIZAJ01' and name <> 'Kolegji Universum O.P';
